# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ....core.serialization import FieldMetadata
from .get_beneficiaries_response_data_rules_payment_types_item_type import (
    GetBeneficiariesResponseDataRulesPaymentTypesItemType,
)


class GetBeneficiariesResponseDataRulesPaymentTypesItem(UniversalBaseModel):
    type: typing.Optional[GetBeneficiariesResponseDataRulesPaymentTypesItemType] = pydantic.Field(default=None)
    """
    Payment method type
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable description of payment type
    """

    required_fields: typing_extensions.Annotated[
        typing.Optional[typing.List["ValidationField"]],
        FieldMetadata(alias="requiredFields"),
        pydantic.Field(alias="requiredFields", description="List of required fields for this payment type"),
    ] = None
    """
    List of required fields for this payment type
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ....types.validation_field import ValidationField  # noqa: E402, I001

update_forward_refs(GetBeneficiariesResponseDataRulesPaymentTypesItem, ValidationField=ValidationField)
