# This file was auto-generated by Fern from our API Definition.

import typing

ListPaymentTypesBeneficiariesResponseDataRulesPaymentTypesItemType = typing.Union[
    typing.Literal["pix", "instapay", "swiftpay_pesonet", "spei", "bank_account", "crypto_wallet", "mobile_money"],
    typing.Any,
]
