# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawDepositWalletAddressesClient, RawDepositWalletAddressesClient
from .types.confirm_deposit_wallet_addresses_response import ConfirmDepositWalletAddressesResponse


class DepositWalletAddressesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDepositWalletAddressesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDepositWalletAddressesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDepositWalletAddressesClient
        """
        return self._raw_client

    def confirm(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConfirmDepositWalletAddressesResponse:
        """
        Confirms and finalizes the deposit wallet addresses for a sender. This should be called after generate-deposit-wallet-addresses to complete the setup process.

        Parameters
        ----------
        id : str
            ID of the sender

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfirmDepositWalletAddressesResponse
            Deposit wallet addresses confirmed successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.senders.deposit_wallet_addresses.confirm(
            id="id",
        )
        """
        _response = self._raw_client.confirm(id, request_options=request_options)
        return _response.data


class AsyncDepositWalletAddressesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDepositWalletAddressesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDepositWalletAddressesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDepositWalletAddressesClient
        """
        return self._raw_client

    async def confirm(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ConfirmDepositWalletAddressesResponse:
        """
        Confirms and finalizes the deposit wallet addresses for a sender. This should be called after generate-deposit-wallet-addresses to complete the setup process.

        Parameters
        ----------
        id : str
            ID of the sender

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfirmDepositWalletAddressesResponse
            Deposit wallet addresses confirmed successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.senders.deposit_wallet_addresses.confirm(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.confirm(id, request_options=request_options)
        return _response.data
