# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AcceptTermsMerchantsResponse,
        AcceptTermsMerchantsResponseData,
        GetBalancesMerchantsResponse,
        GetBalancesMerchantsResponseDataItem,
        GetMerchantsResponse,
        GetMerchantsResponseData,
        GetMerchantsResponseDataAddress,
        GetMerchantsResponseDataKyb,
        GetMerchantsResponseDataKybStatus,
        GetMerchantsResponseDataStatus,
        GetMerchantsResponseDataUbo,
    )
    from . import (
        accounts,
        deposit_wallet_addresses,
        fiat_deposits,
        source_wallet_addresses,
        stablecoin_deposits,
        withdrawals,
    )
    from .accounts import (
        ListAccountsRequestSortBy,
        ListAccountsRequestSortOrder,
        ListAccountsResponse,
        ListAccountsResponseDataItem,
        ListAccountsResponseDataItemCurrency,
    )
    from .deposit_wallet_addresses import (
        ConfirmDepositWalletAddressesResponse,
        ConfirmDepositWalletAddressesResponseDataItem,
        ConfirmDepositWalletAddressesResponseDataItemChain,
        ConfirmDepositWalletAddressesResponseDataItemOwnerType,
        GenerateDepositWalletAddressesResponse,
        GenerateDepositWalletAddressesResponseDataItem,
        GenerateDepositWalletAddressesResponseDataItemChain,
        GenerateDepositWalletAddressesResponseDataItemOwnerType,
    )
    from .fiat_deposits import (
        GetFiatDepositsResponse,
        ListFiatDepositsRequestCurrency,
        ListFiatDepositsRequestSortBy,
        ListFiatDepositsRequestSortOrder,
        ListFiatDepositsResponse,
    )
    from .source_wallet_addresses import (
        CreateSourceWalletAddressesResponse,
        CreateSourceWalletAddressesResponseDataItem,
        CreateSourceWalletAddressesResponseDataItemChain,
        CreateSourceWalletAddressesResponseDataItemOwnerType,
        CreateSourceWalletAddressesResponseDataItemRiskLevel,
        ListSourceWalletAddressesResponse,
        ListSourceWalletAddressesResponseDataItem,
        ListSourceWalletAddressesResponseDataItemChain,
        ListSourceWalletAddressesResponseDataItemOwnerType,
        ListSourceWalletAddressesResponseDataItemRiskLevel,
    )
    from .stablecoin_deposits import (
        GetStablecoinDepositsResponse,
        ListStablecoinDepositsRequestCurrency,
        ListStablecoinDepositsRequestSortBy,
        ListStablecoinDepositsRequestSortOrder,
        ListStablecoinDepositsRequestStatus,
        ListStablecoinDepositsRequestSwaRiskLevel,
        ListStablecoinDepositsResponse,
    )
    from .withdrawals import (
        CreateWithdrawalsRequestCurrency,
        ListWithdrawalsRequestChain,
        ListWithdrawalsRequestCurrency,
        ListWithdrawalsRequestStatus,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "AcceptTermsMerchantsResponse": ".types",
    "AcceptTermsMerchantsResponseData": ".types",
    "ConfirmDepositWalletAddressesResponse": ".deposit_wallet_addresses",
    "ConfirmDepositWalletAddressesResponseDataItem": ".deposit_wallet_addresses",
    "ConfirmDepositWalletAddressesResponseDataItemChain": ".deposit_wallet_addresses",
    "ConfirmDepositWalletAddressesResponseDataItemOwnerType": ".deposit_wallet_addresses",
    "CreateSourceWalletAddressesResponse": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItem": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItemChain": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItemOwnerType": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItemRiskLevel": ".source_wallet_addresses",
    "CreateWithdrawalsRequestCurrency": ".withdrawals",
    "GenerateDepositWalletAddressesResponse": ".deposit_wallet_addresses",
    "GenerateDepositWalletAddressesResponseDataItem": ".deposit_wallet_addresses",
    "GenerateDepositWalletAddressesResponseDataItemChain": ".deposit_wallet_addresses",
    "GenerateDepositWalletAddressesResponseDataItemOwnerType": ".deposit_wallet_addresses",
    "GetBalancesMerchantsResponse": ".types",
    "GetBalancesMerchantsResponseDataItem": ".types",
    "GetFiatDepositsResponse": ".fiat_deposits",
    "GetMerchantsResponse": ".types",
    "GetMerchantsResponseData": ".types",
    "GetMerchantsResponseDataAddress": ".types",
    "GetMerchantsResponseDataKyb": ".types",
    "GetMerchantsResponseDataKybStatus": ".types",
    "GetMerchantsResponseDataStatus": ".types",
    "GetMerchantsResponseDataUbo": ".types",
    "GetStablecoinDepositsResponse": ".stablecoin_deposits",
    "ListAccountsRequestSortBy": ".accounts",
    "ListAccountsRequestSortOrder": ".accounts",
    "ListAccountsResponse": ".accounts",
    "ListAccountsResponseDataItem": ".accounts",
    "ListAccountsResponseDataItemCurrency": ".accounts",
    "ListFiatDepositsRequestCurrency": ".fiat_deposits",
    "ListFiatDepositsRequestSortBy": ".fiat_deposits",
    "ListFiatDepositsRequestSortOrder": ".fiat_deposits",
    "ListFiatDepositsResponse": ".fiat_deposits",
    "ListSourceWalletAddressesResponse": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItem": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItemChain": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItemOwnerType": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItemRiskLevel": ".source_wallet_addresses",
    "ListStablecoinDepositsRequestCurrency": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestSortBy": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestSortOrder": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestStatus": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestSwaRiskLevel": ".stablecoin_deposits",
    "ListStablecoinDepositsResponse": ".stablecoin_deposits",
    "ListWithdrawalsRequestChain": ".withdrawals",
    "ListWithdrawalsRequestCurrency": ".withdrawals",
    "ListWithdrawalsRequestStatus": ".withdrawals",
    "accounts": ".accounts",
    "deposit_wallet_addresses": ".deposit_wallet_addresses",
    "fiat_deposits": ".fiat_deposits",
    "source_wallet_addresses": ".source_wallet_addresses",
    "stablecoin_deposits": ".stablecoin_deposits",
    "withdrawals": ".withdrawals",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AcceptTermsMerchantsResponse",
    "AcceptTermsMerchantsResponseData",
    "ConfirmDepositWalletAddressesResponse",
    "ConfirmDepositWalletAddressesResponseDataItem",
    "ConfirmDepositWalletAddressesResponseDataItemChain",
    "ConfirmDepositWalletAddressesResponseDataItemOwnerType",
    "CreateSourceWalletAddressesResponse",
    "CreateSourceWalletAddressesResponseDataItem",
    "CreateSourceWalletAddressesResponseDataItemChain",
    "CreateSourceWalletAddressesResponseDataItemOwnerType",
    "CreateSourceWalletAddressesResponseDataItemRiskLevel",
    "CreateWithdrawalsRequestCurrency",
    "GenerateDepositWalletAddressesResponse",
    "GenerateDepositWalletAddressesResponseDataItem",
    "GenerateDepositWalletAddressesResponseDataItemChain",
    "GenerateDepositWalletAddressesResponseDataItemOwnerType",
    "GetBalancesMerchantsResponse",
    "GetBalancesMerchantsResponseDataItem",
    "GetFiatDepositsResponse",
    "GetMerchantsResponse",
    "GetMerchantsResponseData",
    "GetMerchantsResponseDataAddress",
    "GetMerchantsResponseDataKyb",
    "GetMerchantsResponseDataKybStatus",
    "GetMerchantsResponseDataStatus",
    "GetMerchantsResponseDataUbo",
    "GetStablecoinDepositsResponse",
    "ListAccountsRequestSortBy",
    "ListAccountsRequestSortOrder",
    "ListAccountsResponse",
    "ListAccountsResponseDataItem",
    "ListAccountsResponseDataItemCurrency",
    "ListFiatDepositsRequestCurrency",
    "ListFiatDepositsRequestSortBy",
    "ListFiatDepositsRequestSortOrder",
    "ListFiatDepositsResponse",
    "ListSourceWalletAddressesResponse",
    "ListSourceWalletAddressesResponseDataItem",
    "ListSourceWalletAddressesResponseDataItemChain",
    "ListSourceWalletAddressesResponseDataItemOwnerType",
    "ListSourceWalletAddressesResponseDataItemRiskLevel",
    "ListStablecoinDepositsRequestCurrency",
    "ListStablecoinDepositsRequestSortBy",
    "ListStablecoinDepositsRequestSortOrder",
    "ListStablecoinDepositsRequestStatus",
    "ListStablecoinDepositsRequestSwaRiskLevel",
    "ListStablecoinDepositsResponse",
    "ListWithdrawalsRequestChain",
    "ListWithdrawalsRequestCurrency",
    "ListWithdrawalsRequestStatus",
    "accounts",
    "deposit_wallet_addresses",
    "fiat_deposits",
    "source_wallet_addresses",
    "stablecoin_deposits",
    "withdrawals",
]
