# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawApiKeysClient, RawApiKeysClient
from .types.create_api_keys_response import CreateApiKeysResponse
from .types.get_api_keys_response import GetApiKeysResponse
from .types.list_api_keys_request_sort_by import ListApiKeysRequestSortBy
from .types.list_api_keys_request_sort_order import ListApiKeysRequestSortOrder
from .types.list_api_keys_response import ListApiKeysResponse
from .types.update_api_keys_response import UpdateApiKeysResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ApiKeysClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawApiKeysClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ListApiKeysRequestSortBy] = None,
        sort_order: typing.Optional[ListApiKeysRequestSortOrder] = None,
        search: typing.Optional[str] = None,
        merchant_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListApiKeysResponse:
        """
        Retrieves a paginated list of API keys for the merchant.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (zero-based)

        page_size : typing.Optional[int]
            Number of items per page

        sort_by : typing.Optional[ListApiKeysRequestSortBy]
            Field to sort by

        sort_order : typing.Optional[ListApiKeysRequestSortOrder]
            Sort direction

        search : typing.Optional[str]
            Search filter

        merchant_id : typing.Optional[str]
            Filter by merchant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListApiKeysResponse
            API keys retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.api_keys.list()
        """
        _response = self._raw_client.list(
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            merchant_id=merchant_id,
            request_options=request_options,
        )
        return _response.data

    def create(
        self, *, name: str, permissions: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> CreateApiKeysResponse:
        """
        Creates a new API key for the merchant. The API secret is only returned in the creation response and cannot be retrieved later.

        Parameters
        ----------
        name : str
            Human-readable name for the API key

        permissions : typing.Sequence[str]
            List of permissions to grant to this API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateApiKeysResponse
            API key created successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.api_keys.create(
            name="name",
            permissions=["permissions"],
        )
        """
        _response = self._raw_client.create(name=name, permissions=permissions, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetApiKeysResponse:
        """
        Retrieves details of a specific API key by ID.

        Parameters
        ----------
        id : str
            ID of the API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiKeysResponse
            API key retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.api_keys.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes an API key. This action cannot be undone.

        Parameters
        ----------
        id : str
            ID of the API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.api_keys.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        permissions: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateApiKeysResponse:
        """
        Updates the name and/or permissions of an existing API key.

        Parameters
        ----------
        id : str
            ID of the API key

        name : typing.Optional[str]
            Updated name for the API key

        permissions : typing.Optional[typing.Sequence[str]]
            Updated list of permissions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateApiKeysResponse
            API key updated successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.api_keys.update(
            id="id",
        )
        """
        _response = self._raw_client.update(id, name=name, permissions=permissions, request_options=request_options)
        return _response.data


class AsyncApiKeysClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawApiKeysClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawApiKeysClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawApiKeysClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ListApiKeysRequestSortBy] = None,
        sort_order: typing.Optional[ListApiKeysRequestSortOrder] = None,
        search: typing.Optional[str] = None,
        merchant_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListApiKeysResponse:
        """
        Retrieves a paginated list of API keys for the merchant.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (zero-based)

        page_size : typing.Optional[int]
            Number of items per page

        sort_by : typing.Optional[ListApiKeysRequestSortBy]
            Field to sort by

        sort_order : typing.Optional[ListApiKeysRequestSortOrder]
            Sort direction

        search : typing.Optional[str]
            Search filter

        merchant_id : typing.Optional[str]
            Filter by merchant ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListApiKeysResponse
            API keys retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_keys.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            merchant_id=merchant_id,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self, *, name: str, permissions: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> CreateApiKeysResponse:
        """
        Creates a new API key for the merchant. The API secret is only returned in the creation response and cannot be retrieved later.

        Parameters
        ----------
        name : str
            Human-readable name for the API key

        permissions : typing.Sequence[str]
            List of permissions to grant to this API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateApiKeysResponse
            API key created successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_keys.create(
                name="name",
                permissions=["permissions"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(name=name, permissions=permissions, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetApiKeysResponse:
        """
        Retrieves details of a specific API key by ID.

        Parameters
        ----------
        id : str
            ID of the API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetApiKeysResponse
            API key retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_keys.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes an API key. This action cannot be undone.

        Parameters
        ----------
        id : str
            ID of the API key

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_keys.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        permissions: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateApiKeysResponse:
        """
        Updates the name and/or permissions of an existing API key.

        Parameters
        ----------
        id : str
            ID of the API key

        name : typing.Optional[str]
            Updated name for the API key

        permissions : typing.Optional[typing.Sequence[str]]
            Updated list of permissions

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateApiKeysResponse
            API key updated successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.api_keys.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id, name=name, permissions=permissions, request_options=request_options
        )
        return _response.data
