# This file was auto-generated by Fern from our API Definition.

import typing

CreateTransfersResponseDataStatus = typing.Union[
    typing.Literal["created", "funds_received", "in_progress", "success", "failed"], typing.Any
]
