# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .merchant_login_auth_response_data_user_scope import MerchantLoginAuthResponseDataUserScope


class MerchantLoginAuthResponseDataUser(UniversalBaseModel):
    """
    Authenticated user details
    """

    id: typing.Optional[str] = None
    email: typing.Optional[str] = None
    first_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="firstName"), pydantic.Field(alias="firstName")
    ] = None
    last_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastName"), pydantic.Field(alias="lastName")
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    User account status
    """

    merchant_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="merchantId"), pydantic.Field(alias="merchantId")
    ] = None
    scope: typing.Optional[MerchantLoginAuthResponseDataUserScope] = None
    is_mfa_configured: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isMfaConfigured"), pydantic.Field(alias="isMfaConfigured")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
