# This file was auto-generated by Fern from our API Definition.

import typing

ListEventsRequestAggregateType = typing.Union[
    typing.Literal["order", "merchant", "transaction", "sender", "batch_order", "beneficiary"], typing.Any
]
