# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAuthClient, RawAuthClient
from .types.authorize_auth_request_permission_check_type import AuthorizeAuthRequestPermissionCheckType
from .types.authorize_auth_response import AuthorizeAuthResponse
from .types.merchant_login_auth_response import MerchantLoginAuthResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AuthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAuthClient
        """
        return self._raw_client

    def merchant_login(
        self,
        *,
        email: str,
        password: str,
        totp: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MerchantLoginAuthResponse:
        """
        Authenticates a merchant user with email and password. Returns access and refresh tokens upon successful authentication. Supports MFA via TOTP.

        Parameters
        ----------
        email : str
            Merchant user email address

        password : str
            Account password

        totp : typing.Optional[str]
            Time-based one-time password for MFA (if MFA is enabled)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MerchantLoginAuthResponse
            Authentication successful

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.auth.merchant_login(
            email="email",
            password="password",
        )
        """
        _response = self._raw_client.merchant_login(
            email=email, password=password, totp=totp, request_options=request_options
        )
        return _response.data

    def authorize(
        self,
        *,
        host: typing.Optional[str] = OMIT,
        authorization_header: typing.Optional[str] = OMIT,
        permissions_required: typing.Optional[typing.Sequence[str]] = OMIT,
        permission_check_type: typing.Optional[AuthorizeAuthRequestPermissionCheckType] = OMIT,
        should_authorize: typing.Optional[bool] = OMIT,
        api_key: typing.Optional[str] = OMIT,
        api_secret: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthorizeAuthResponse:
        """
        Validates an access token or API key and returns the authenticated principal with their permissions. Used internally for request authorization.

        Parameters
        ----------
        host : typing.Optional[str]
            The host of the originating request

        authorization_header : typing.Optional[str]
            The Authorization header value (Bearer token)

        permissions_required : typing.Optional[typing.Sequence[str]]
            List of permissions required for the request

        permission_check_type : typing.Optional[AuthorizeAuthRequestPermissionCheckType]
            Whether all permissions are required (and) or any one suffices (or)

        should_authorize : typing.Optional[bool]
            Whether to enforce permission checks

        api_key : typing.Optional[str]
            API key for key-based authentication

        api_secret : typing.Optional[str]
            API secret for key-based authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthorizeAuthResponse
            Authorization successful

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.auth.authorize()
        """
        _response = self._raw_client.authorize(
            host=host,
            authorization_header=authorization_header,
            permissions_required=permissions_required,
            permission_check_type=permission_check_type,
            should_authorize=should_authorize,
            api_key=api_key,
            api_secret=api_secret,
            request_options=request_options,
        )
        return _response.data


class AsyncAuthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAuthClient
        """
        return self._raw_client

    async def merchant_login(
        self,
        *,
        email: str,
        password: str,
        totp: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MerchantLoginAuthResponse:
        """
        Authenticates a merchant user with email and password. Returns access and refresh tokens upon successful authentication. Supports MFA via TOTP.

        Parameters
        ----------
        email : str
            Merchant user email address

        password : str
            Account password

        totp : typing.Optional[str]
            Time-based one-time password for MFA (if MFA is enabled)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MerchantLoginAuthResponse
            Authentication successful

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.merchant_login(
                email="email",
                password="password",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.merchant_login(
            email=email, password=password, totp=totp, request_options=request_options
        )
        return _response.data

    async def authorize(
        self,
        *,
        host: typing.Optional[str] = OMIT,
        authorization_header: typing.Optional[str] = OMIT,
        permissions_required: typing.Optional[typing.Sequence[str]] = OMIT,
        permission_check_type: typing.Optional[AuthorizeAuthRequestPermissionCheckType] = OMIT,
        should_authorize: typing.Optional[bool] = OMIT,
        api_key: typing.Optional[str] = OMIT,
        api_secret: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AuthorizeAuthResponse:
        """
        Validates an access token or API key and returns the authenticated principal with their permissions. Used internally for request authorization.

        Parameters
        ----------
        host : typing.Optional[str]
            The host of the originating request

        authorization_header : typing.Optional[str]
            The Authorization header value (Bearer token)

        permissions_required : typing.Optional[typing.Sequence[str]]
            List of permissions required for the request

        permission_check_type : typing.Optional[AuthorizeAuthRequestPermissionCheckType]
            Whether all permissions are required (and) or any one suffices (or)

        should_authorize : typing.Optional[bool]
            Whether to enforce permission checks

        api_key : typing.Optional[str]
            API key for key-based authentication

        api_secret : typing.Optional[str]
            API secret for key-based authentication

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AuthorizeAuthResponse
            Authorization successful

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.authorize()


        asyncio.run(main())
        """
        _response = await self._raw_client.authorize(
            host=host,
            authorization_header=authorization_header,
            permissions_required=permissions_required,
            permission_check_type=permission_check_type,
            should_authorize=should_authorize,
            api_key=api_key,
            api_secret=api_secret,
            request_options=request_options,
        )
        return _response.data
