# This file was auto-generated by Fern from our API Definition.

import typing

CreateUbosRequestPepQuestionnaireSelfPepCategory = typing.Union[
    typing.Literal["DOMESTIC", "FOREIGN", "INTERNATIONAL_ORGANIZATION"], typing.Any
]
