# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .create_v2ubos_request_pep_questionnaire_association import CreateV2UbosRequestPepQuestionnaireAssociation
from .create_v2ubos_request_pep_questionnaire_declaration_type import CreateV2UbosRequestPepQuestionnaireDeclarationType
from .create_v2ubos_request_pep_questionnaire_self import CreateV2UbosRequestPepQuestionnaireSelf


class CreateV2UbosRequestPepQuestionnaire(UniversalBaseModel):
    """
    Required when `pepDeclaration` is true. Contains declarationType with conditional `self` or `association` sections.
    """

    declaration_type: typing_extensions.Annotated[
        typing.Optional[CreateV2UbosRequestPepQuestionnaireDeclarationType],
        FieldMetadata(alias="declarationType"),
        pydantic.Field(alias="declarationType", description="PEP declaration type."),
    ] = None
    """
    PEP declaration type.
    """

    self_: typing_extensions.Annotated[
        typing.Optional[CreateV2UbosRequestPepQuestionnaireSelf],
        FieldMetadata(alias="self"),
        pydantic.Field(alias="self", description="Required when declarationType is SELF."),
    ] = None
    """
    Required when declarationType is SELF.
    """

    association: typing.Optional[CreateV2UbosRequestPepQuestionnaireAssociation] = pydantic.Field(default=None)
    """
    Required when declarationType is IMMEDIATE_FAMILY or CLOSE_ASSOCIATE.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
