# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .create_v1ubos_request_identity_document_type import CreateV1UbosRequestIdentityDocumentType


class CreateV1UbosRequestIdentity(UniversalBaseModel):
    """
    Ultimate Beneficial Owner information. Note: Document requirements (documentFront, documentBack) vary by country. Please refer to the validation-rules endpoint with ownerType='ubo' and the specific country to determine exact documentation requirements.
    """

    document_type: typing_extensions.Annotated[
        CreateV1UbosRequestIdentityDocumentType,
        FieldMetadata(alias="documentType"),
        pydantic.Field(alias="documentType", description="Type of identity document."),
    ]
    """
    Type of identity document.
    """

    country_code: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="countryCode"),
        pydantic.Field(alias="countryCode", description="Country code of the identity document."),
    ]
    """
    Country code of the identity document.
    """

    document_front: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="documentFront"),
        pydantic.Field(
            alias="documentFront",
            description="Base64 encoded front image of identity document. Required for certain countries - check validation-rules endpoint.",
        ),
    ] = None
    """
    Base64 encoded front image of identity document. Required for certain countries - check validation-rules endpoint.
    """

    document_back: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="documentBack"),
        pydantic.Field(
            alias="documentBack",
            description="Base64 encoded back image of identity document. Required for certain countries - check validation-rules endpoint.",
        ),
    ] = None
    """
    Base64 encoded back image of identity document. Required for certain countries - check validation-rules endpoint.
    """

    document_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="documentNumber"),
        pydantic.Field(alias="documentNumber", description="The number of the selected documentType"),
    ]
    """
    The number of the selected documentType
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
