# This file was auto-generated by Fern from our API Definition.

import typing

UpdateUbosResponseDataDocumentsItemType = typing.Union[
    typing.Literal["source_of_funds", "verification_report"], typing.Any
]
