# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import encode_path_param
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...errors.bad_request_error import BadRequestError
from ...errors.forbidden_error import ForbiddenError
from ...errors.internal_server_error import InternalServerError
from ...errors.not_found_error import NotFoundError
from ...errors.unauthorized_error import UnauthorizedError
from ...types.error_response import ErrorResponse
from .types.generate_eur_gbp_deposit_bank_accounts_request_currency import (
    GenerateEurGbpDepositBankAccountsRequestCurrency,
)
from .types.generate_eur_gbp_deposit_bank_accounts_response import GenerateEurGbpDepositBankAccountsResponse
from .types.generate_on_demand_deposit_bank_accounts_request_currency import (
    GenerateOnDemandDepositBankAccountsRequestCurrency,
)
from .types.generate_on_demand_deposit_bank_accounts_response import GenerateOnDemandDepositBankAccountsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawDepositBankAccountsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def generate_eur_gbp(
        self,
        id: str,
        *,
        currency: GenerateEurGbpDepositBankAccountsRequestCurrency,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GenerateEurGbpDepositBankAccountsResponse]:
        """
        **Deprecated.** Use [`POST /v1/senders/{id}/generate-ondemand-deposit-bank-accounts`](#post_v1-senders-id-generate-ondemand-deposit-bank-accounts) instead.

        Initiates the creation of EUR or GBP virtual IBAN deposit bank accounts for a sender. This is an asynchronous operation that may take up to 60 seconds to complete.

        Parameters
        ----------
        id : str
            ID of the sender

        currency : GenerateEurGbpDepositBankAccountsRequestCurrency
            The currency for the deposit bank account. Only EUR and GBP are supported.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GenerateEurGbpDepositBankAccountsResponse]
            Deposit bank account creation initiated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/senders/{encode_path_param(id)}/generate-eur-gbp-deposit-bank-accounts",
            method="POST",
            json={
                "currency": currency,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateEurGbpDepositBankAccountsResponse,
                    parse_obj_as(
                        type_=GenerateEurGbpDepositBankAccountsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def generate_on_demand(
        self,
        id: str,
        *,
        currency: GenerateOnDemandDepositBankAccountsRequestCurrency,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GenerateOnDemandDepositBankAccountsResponse]:
        """
        Initiates the creation of a deposit bank account for a sender on demand, in the requested currency.

        Parameters
        ----------
        id : str
            ID of the sender

        currency : GenerateOnDemandDepositBankAccountsRequestCurrency
            The currency for the deposit bank account.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GenerateOnDemandDepositBankAccountsResponse]
            Deposit bank account creation initiated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/senders/{encode_path_param(id)}/generate-ondemand-deposit-bank-accounts",
            method="POST",
            json={
                "currency": currency,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateOnDemandDepositBankAccountsResponse,
                    parse_obj_as(
                        type_=GenerateOnDemandDepositBankAccountsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDepositBankAccountsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def generate_eur_gbp(
        self,
        id: str,
        *,
        currency: GenerateEurGbpDepositBankAccountsRequestCurrency,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GenerateEurGbpDepositBankAccountsResponse]:
        """
        **Deprecated.** Use [`POST /v1/senders/{id}/generate-ondemand-deposit-bank-accounts`](#post_v1-senders-id-generate-ondemand-deposit-bank-accounts) instead.

        Initiates the creation of EUR or GBP virtual IBAN deposit bank accounts for a sender. This is an asynchronous operation that may take up to 60 seconds to complete.

        Parameters
        ----------
        id : str
            ID of the sender

        currency : GenerateEurGbpDepositBankAccountsRequestCurrency
            The currency for the deposit bank account. Only EUR and GBP are supported.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GenerateEurGbpDepositBankAccountsResponse]
            Deposit bank account creation initiated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/senders/{encode_path_param(id)}/generate-eur-gbp-deposit-bank-accounts",
            method="POST",
            json={
                "currency": currency,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateEurGbpDepositBankAccountsResponse,
                    parse_obj_as(
                        type_=GenerateEurGbpDepositBankAccountsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def generate_on_demand(
        self,
        id: str,
        *,
        currency: GenerateOnDemandDepositBankAccountsRequestCurrency,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GenerateOnDemandDepositBankAccountsResponse]:
        """
        Initiates the creation of a deposit bank account for a sender on demand, in the requested currency.

        Parameters
        ----------
        id : str
            ID of the sender

        currency : GenerateOnDemandDepositBankAccountsRequestCurrency
            The currency for the deposit bank account.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GenerateOnDemandDepositBankAccountsResponse]
            Deposit bank account creation initiated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/senders/{encode_path_param(id)}/generate-ondemand-deposit-bank-accounts",
            method="POST",
            json={
                "currency": currency,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateOnDemandDepositBankAccountsResponse,
                    parse_obj_as(
                        type_=GenerateOnDemandDepositBankAccountsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
