# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .get_v2senders_response_data_rules_ubo_required_fields_item import (
    GetV2SendersResponseDataRulesUboRequiredFieldsItem,
)


class GetV2SendersResponseDataRulesUbo(UniversalBaseModel):
    """
    UBO validation rules (only present for business ownerType)
    """

    required_fields: typing_extensions.Annotated[
        typing.Optional[typing.List[GetV2SendersResponseDataRulesUboRequiredFieldsItem]],
        FieldMetadata(alias="requiredFields"),
        pydantic.Field(
            alias="requiredFields",
            description="Required fields for UBO. Identity fields include supportedDocumentTypes.",
        ),
    ] = None
    """
    Required fields for UBO. Identity fields include supportedDocumentTypes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
