# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawDocumentsClient, RawDocumentsClient
from .types.get_presigned_url_documents_response import GetPresignedUrlDocumentsResponse


class DocumentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDocumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDocumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDocumentsClient
        """
        return self._raw_client

    def get_presigned_url(
        self, order_id: str, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPresignedUrlDocumentsResponse:
        """
        Retrieves a temporary presigned URL for downloading an order document. The URL expires after 5 minutes.

        Parameters
        ----------
        order_id : str
            ID of the order

        document_id : str
            ID of the document

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPresignedUrlDocumentsResponse
            Presigned URL generated successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.documents.get_presigned_url(
            order_id="orderId",
            document_id="documentId",
        )
        """
        _response = self._raw_client.get_presigned_url(order_id, document_id, request_options=request_options)
        return _response.data


class AsyncDocumentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDocumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDocumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDocumentsClient
        """
        return self._raw_client

    async def get_presigned_url(
        self, order_id: str, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPresignedUrlDocumentsResponse:
        """
        Retrieves a temporary presigned URL for downloading an order document. The URL expires after 5 minutes.

        Parameters
        ----------
        order_id : str
            ID of the order

        document_id : str
            ID of the document

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPresignedUrlDocumentsResponse
            Presigned URL generated successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.documents.get_presigned_url(
                order_id="orderId",
                document_id="documentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_presigned_url(order_id, document_id, request_options=request_options)
        return _response.data
