# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bank_account_type import BankAccountType


class BankAccountInfo(UniversalBaseModel):
    """
    Bank account payment method data
    """

    account_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="accountNumber"),
        pydantic.Field(alias="accountNumber", description="Bank account number"),
    ]
    """
    Bank account number
    """

    account_type: typing_extensions.Annotated[
        typing.Optional[BankAccountType], FieldMetadata(alias="accountType"), pydantic.Field(alias="accountType")
    ] = None
    ifsc_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ifscCode"),
        pydantic.Field(alias="ifscCode", description="IFSC code (India)"),
    ] = None
    """
    IFSC code (India)
    """

    bic: typing.Optional[str] = pydantic.Field(default=None)
    """
    BIC/SWIFT code (Europe)
    """

    sort_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sortCode"),
        pydantic.Field(alias="sortCode", description="Sort code (UK)"),
    ] = None
    """
    Sort code (UK)
    """

    routing_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="routingNumber"),
        pydantic.Field(alias="routingNumber", description="Routing number (US, CA)"),
    ] = None
    """
    Routing number (US, CA)
    """

    branch_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="branchCode"),
        pydantic.Field(alias="branchCode", description="Branch code (CA, JP)"),
    ] = None
    """
    Branch code (CA, JP)
    """

    bsb_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bsbNumber"),
        pydantic.Field(alias="bsbNumber", description="BSB number (AU)"),
    ] = None
    """
    BSB number (AU)
    """

    remittance_purpose: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="remittancePurpose"),
        pydantic.Field(alias="remittancePurpose", description="Remittance purpose (AU, AE)"),
    ] = None
    """
    Remittance purpose (AU, AE)
    """

    transfer_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transferType"),
        pydantic.Field(alias="transferType", description="Transfer type"),
    ] = None
    """
    Transfer type
    """

    bank_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankName"),
        pydantic.Field(alias="bankName", description="Name of the bank"),
    ] = None
    """
    Name of the bank
    """

    bank_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankAddress"),
        pydantic.Field(alias="bankAddress", description="Bank address"),
    ] = None
    """
    Bank address
    """

    bank_city: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bankCity"), pydantic.Field(alias="bankCity", description="Bank city")
    ] = None
    """
    Bank city
    """

    bank_post_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankPostCode"),
        pydantic.Field(alias="bankPostCode", description="Bank postal code"),
    ] = None
    """
    Bank postal code
    """

    bank_state: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankState"),
        pydantic.Field(alias="bankState", description="Bank state"),
    ] = None
    """
    Bank state
    """

    bank_document_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankDocumentNumber"),
        pydantic.Field(alias="bankDocumentNumber", description="Bank document number (used for hand-off payments)"),
    ] = None
    """
    Bank document number (used for hand-off payments)
    """

    bank_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankId"),
        pydantic.Field(alias="bankId", description="Bank identifier number"),
    ] = None
    """
    Bank identifier number
    """

    bank_account_country: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankAccountCountry"),
        pydantic.Field(
            alias="bankAccountCountry", description="Two-letter country code of the bank account (ISO 3166-1 alpha-2)"
        ),
    ] = None
    """
    Two-letter country code of the bank account (ISO 3166-1 alpha-2)
    """

    bank_country: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="bankCountry"),
        pydantic.Field(
            alias="bankCountry", description="Country code of the bank. May be returned alongside bankAccountCountry."
        ),
    ] = None
    """
    Country code of the bank. May be returned alongside bankAccountCountry.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
