# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ErrorResponseError(UniversalBaseModel):
    """
    Error details
    """

    code: typing_extensions.Annotated[
        str, FieldMetadata(alias="CODE"), pydantic.Field(alias="CODE", description="Machine-readable error code")
    ]
    """
    Machine-readable error code
    """

    message: typing_extensions.Annotated[
        str, FieldMetadata(alias="MESSAGE"), pydantic.Field(alias="MESSAGE", description="Human-readable error message")
    ]
    """
    Human-readable error message
    """

    details: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="DETAILS"),
        pydantic.Field(alias="DETAILS", description="Additional error details for validation errors"),
    ] = None
    """
    Additional error details for validation errors
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
