# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class IndividualBeneficiaryAddress(UniversalBaseModel):
    """
    Postal address.
    """

    street: str = pydantic.Field()
    """
    Street address.
    """

    street2: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional street address line.
    """

    city: str = pydantic.Field()
    """
    City.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State or province (ISO 3166-2 format, e.g. US-CA).
    """

    postal_code: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="postalCode"),
        pydantic.Field(
            alias="postalCode", description="Postal/ZIP code. Use '00000' for countries without postal code systems"
        ),
    ]
    """
    Postal/ZIP code. Use '00000' for countries without postal code systems
    """

    country: str = pydantic.Field()
    """
    Country (ISO 3166-1 alpha-2 code).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
