# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class InstapayInfoExtendInfo(UniversalBaseModel):
    recipient_account_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="recipientAccountNumber"),
        pydantic.Field(alias="recipientAccountNumber", description="Recipient account number"),
    ]
    """
    Recipient account number
    """

    recipient_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="recipientName"), pydantic.Field(alias="recipientName", description="Recipient name")
    ]
    """
    Recipient name
    """

    recipient_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="recipientAddress"),
        pydantic.Field(alias="recipientAddress", description="Recipient address"),
    ] = None
    """
    Recipient address
    """

    remarks: typing.Optional[str] = pydantic.Field(default=None)
    """
    Remarks
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
