# This file was auto-generated by Fern from our API Definition.

import typing

SelfieVerificationSessionStatus = typing.Union[
    typing.Literal["NOT_STARTED", "RUNNING", "PENDING", "APPROVED", "DECLINED", "EXPIRED"], typing.Any
]
