# This file was auto-generated by Fern from our API Definition.

import typing

StablecoinDepositStatus = typing.Union[
    typing.Literal["created", "compliance_review_required", "compliance_review_succeeded", "compliance_review_failed"],
    typing.Any,
]
