# This file was auto-generated by Fern from our API Definition.

import typing

VerifySenderRequirementsBlockerCode = typing.Union[
    typing.Literal["missing_data", "missing_associate", "mesta_admin_action_required"], typing.Any
]
