
# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateUbosRequestAddress,
        CreateUbosRequestIdentity,
        CreateUbosRequestIdentityDocumentType,
        CreateUbosRequestPepQuestionnaire,
        CreateUbosRequestPepQuestionnaireAssociation,
        CreateUbosRequestPepQuestionnaireDeclarationType,
        CreateUbosRequestPepQuestionnaireSelf,
        CreateUbosRequestPepQuestionnaireSelfPepCategory,
        CreateUbosResponse,
        CreateUbosResponseData,
        CreateUbosResponseDataDocumentsItem,
        CreateUbosResponseDataDocumentsItemType,
        CreateUbosResponseDataKyc,
        CreateUbosResponseDataKycStatus,
        CreateUbosResponseDataPepQuestionnaire,
        CreateUbosResponseDataPepQuestionnaireAssociation,
        CreateUbosResponseDataPepQuestionnaireDeclarationType,
        CreateUbosResponseDataPepQuestionnaireSelf,
        CreateUbosResponseDataPepQuestionnaireSelfPepCategory,
        DeleteUbosResponse,
        GetUbosResponse,
        GetUbosResponseData,
        GetUbosResponseDataAddress,
        GetUbosResponseDataDocumentsItem,
        GetUbosResponseDataDocumentsItemType,
        GetUbosResponseDataIdentity,
        GetUbosResponseDataIdentityDocumentBack,
        GetUbosResponseDataIdentityDocumentFront,
        GetUbosResponseDataIdentityDocumentType,
        GetUbosResponseDataKyc,
        GetUbosResponseDataKycStatus,
        GetUbosResponseDataSender,
        GetUbosResponseDataSenderAddressesItem,
        GetUbosResponseDataSenderDocumentsItem,
        GetUbosResponseDataSenderKyb,
        GetUbosResponseDataSenderKyc,
        GetUbosResponseDataSenderStatus,
        GetUbosResponseDataSenderTos,
        GetUbosResponseDataSenderType,
        GetVerificationUrlUbosRequestAction,
        GetVerificationUrlUbosResponse,
        GetVerificationUrlUbosResponseData,
        GetVerificationUrlUbosResponseDataLatestSession,
        GetVerificationUrlUbosResponseDataLatestSessionStatus,
        GetVerificationUrlUbosResponseDataPreviousSessionsItem,
        GetVerificationUrlUbosResponseDataPreviousSessionsItemStatus,
        UpdateUbosRequestIdentity,
        UpdateUbosRequestIdentityDocumentType,
        UpdateUbosRequestPepQuestionnaire,
        UpdateUbosRequestPepQuestionnaireAssociation,
        UpdateUbosRequestPepQuestionnaireDeclarationType,
        UpdateUbosRequestPepQuestionnaireSelf,
        UpdateUbosRequestPepQuestionnaireSelfPepCategory,
        UpdateUbosResponse,
        UpdateUbosResponseData,
        UpdateUbosResponseDataAddress,
        UpdateUbosResponseDataDocumentsItem,
        UpdateUbosResponseDataDocumentsItemType,
        UpdateUbosResponseDataIdentity,
        UpdateUbosResponseDataIdentityDocumentType,
        UpdateUbosResponseDataKyc,
        UpdateUbosResponseDataKycStatus,
        UpdateUbosResponseDataPepQuestionnaire,
        UpdateUbosResponseDataPepQuestionnaireAssociation,
        UpdateUbosResponseDataPepQuestionnaireDeclarationType,
        UpdateUbosResponseDataPepQuestionnaireSelf,
        UpdateUbosResponseDataPepQuestionnaireSelfPepCategory,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateUbosRequestAddress": ".types",
    "CreateUbosRequestIdentity": ".types",
    "CreateUbosRequestIdentityDocumentType": ".types",
    "CreateUbosRequestPepQuestionnaire": ".types",
    "CreateUbosRequestPepQuestionnaireAssociation": ".types",
    "CreateUbosRequestPepQuestionnaireDeclarationType": ".types",
    "CreateUbosRequestPepQuestionnaireSelf": ".types",
    "CreateUbosRequestPepQuestionnaireSelfPepCategory": ".types",
    "CreateUbosResponse": ".types",
    "CreateUbosResponseData": ".types",
    "CreateUbosResponseDataDocumentsItem": ".types",
    "CreateUbosResponseDataDocumentsItemType": ".types",
    "CreateUbosResponseDataKyc": ".types",
    "CreateUbosResponseDataKycStatus": ".types",
    "CreateUbosResponseDataPepQuestionnaire": ".types",
    "CreateUbosResponseDataPepQuestionnaireAssociation": ".types",
    "CreateUbosResponseDataPepQuestionnaireDeclarationType": ".types",
    "CreateUbosResponseDataPepQuestionnaireSelf": ".types",
    "CreateUbosResponseDataPepQuestionnaireSelfPepCategory": ".types",
    "DeleteUbosResponse": ".types",
    "GetUbosResponse": ".types",
    "GetUbosResponseData": ".types",
    "GetUbosResponseDataAddress": ".types",
    "GetUbosResponseDataDocumentsItem": ".types",
    "GetUbosResponseDataDocumentsItemType": ".types",
    "GetUbosResponseDataIdentity": ".types",
    "GetUbosResponseDataIdentityDocumentBack": ".types",
    "GetUbosResponseDataIdentityDocumentFront": ".types",
    "GetUbosResponseDataIdentityDocumentType": ".types",
    "GetUbosResponseDataKyc": ".types",
    "GetUbosResponseDataKycStatus": ".types",
    "GetUbosResponseDataSender": ".types",
    "GetUbosResponseDataSenderAddressesItem": ".types",
    "GetUbosResponseDataSenderDocumentsItem": ".types",
    "GetUbosResponseDataSenderKyb": ".types",
    "GetUbosResponseDataSenderKyc": ".types",
    "GetUbosResponseDataSenderStatus": ".types",
    "GetUbosResponseDataSenderTos": ".types",
    "GetUbosResponseDataSenderType": ".types",
    "GetVerificationUrlUbosRequestAction": ".types",
    "GetVerificationUrlUbosResponse": ".types",
    "GetVerificationUrlUbosResponseData": ".types",
    "GetVerificationUrlUbosResponseDataLatestSession": ".types",
    "GetVerificationUrlUbosResponseDataLatestSessionStatus": ".types",
    "GetVerificationUrlUbosResponseDataPreviousSessionsItem": ".types",
    "GetVerificationUrlUbosResponseDataPreviousSessionsItemStatus": ".types",
    "UpdateUbosRequestIdentity": ".types",
    "UpdateUbosRequestIdentityDocumentType": ".types",
    "UpdateUbosRequestPepQuestionnaire": ".types",
    "UpdateUbosRequestPepQuestionnaireAssociation": ".types",
    "UpdateUbosRequestPepQuestionnaireDeclarationType": ".types",
    "UpdateUbosRequestPepQuestionnaireSelf": ".types",
    "UpdateUbosRequestPepQuestionnaireSelfPepCategory": ".types",
    "UpdateUbosResponse": ".types",
    "UpdateUbosResponseData": ".types",
    "UpdateUbosResponseDataAddress": ".types",
    "UpdateUbosResponseDataDocumentsItem": ".types",
    "UpdateUbosResponseDataDocumentsItemType": ".types",
    "UpdateUbosResponseDataIdentity": ".types",
    "UpdateUbosResponseDataIdentityDocumentType": ".types",
    "UpdateUbosResponseDataKyc": ".types",
    "UpdateUbosResponseDataKycStatus": ".types",
    "UpdateUbosResponseDataPepQuestionnaire": ".types",
    "UpdateUbosResponseDataPepQuestionnaireAssociation": ".types",
    "UpdateUbosResponseDataPepQuestionnaireDeclarationType": ".types",
    "UpdateUbosResponseDataPepQuestionnaireSelf": ".types",
    "UpdateUbosResponseDataPepQuestionnaireSelfPepCategory": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateUbosRequestAddress",
    "CreateUbosRequestIdentity",
    "CreateUbosRequestIdentityDocumentType",
    "CreateUbosRequestPepQuestionnaire",
    "CreateUbosRequestPepQuestionnaireAssociation",
    "CreateUbosRequestPepQuestionnaireDeclarationType",
    "CreateUbosRequestPepQuestionnaireSelf",
    "CreateUbosRequestPepQuestionnaireSelfPepCategory",
    "CreateUbosResponse",
    "CreateUbosResponseData",
    "CreateUbosResponseDataDocumentsItem",
    "CreateUbosResponseDataDocumentsItemType",
    "CreateUbosResponseDataKyc",
    "CreateUbosResponseDataKycStatus",
    "CreateUbosResponseDataPepQuestionnaire",
    "CreateUbosResponseDataPepQuestionnaireAssociation",
    "CreateUbosResponseDataPepQuestionnaireDeclarationType",
    "CreateUbosResponseDataPepQuestionnaireSelf",
    "CreateUbosResponseDataPepQuestionnaireSelfPepCategory",
    "DeleteUbosResponse",
    "GetUbosResponse",
    "GetUbosResponseData",
    "GetUbosResponseDataAddress",
    "GetUbosResponseDataDocumentsItem",
    "GetUbosResponseDataDocumentsItemType",
    "GetUbosResponseDataIdentity",
    "GetUbosResponseDataIdentityDocumentBack",
    "GetUbosResponseDataIdentityDocumentFront",
    "GetUbosResponseDataIdentityDocumentType",
    "GetUbosResponseDataKyc",
    "GetUbosResponseDataKycStatus",
    "GetUbosResponseDataSender",
    "GetUbosResponseDataSenderAddressesItem",
    "GetUbosResponseDataSenderDocumentsItem",
    "GetUbosResponseDataSenderKyb",
    "GetUbosResponseDataSenderKyc",
    "GetUbosResponseDataSenderStatus",
    "GetUbosResponseDataSenderTos",
    "GetUbosResponseDataSenderType",
    "GetVerificationUrlUbosRequestAction",
    "GetVerificationUrlUbosResponse",
    "GetVerificationUrlUbosResponseData",
    "GetVerificationUrlUbosResponseDataLatestSession",
    "GetVerificationUrlUbosResponseDataLatestSessionStatus",
    "GetVerificationUrlUbosResponseDataPreviousSessionsItem",
    "GetVerificationUrlUbosResponseDataPreviousSessionsItemStatus",
    "UpdateUbosRequestIdentity",
    "UpdateUbosRequestIdentityDocumentType",
    "UpdateUbosRequestPepQuestionnaire",
    "UpdateUbosRequestPepQuestionnaireAssociation",
    "UpdateUbosRequestPepQuestionnaireDeclarationType",
    "UpdateUbosRequestPepQuestionnaireSelf",
    "UpdateUbosRequestPepQuestionnaireSelfPepCategory",
    "UpdateUbosResponse",
    "UpdateUbosResponseData",
    "UpdateUbosResponseDataAddress",
    "UpdateUbosResponseDataDocumentsItem",
    "UpdateUbosResponseDataDocumentsItemType",
    "UpdateUbosResponseDataIdentity",
    "UpdateUbosResponseDataIdentityDocumentType",
    "UpdateUbosResponseDataKyc",
    "UpdateUbosResponseDataKycStatus",
    "UpdateUbosResponseDataPepQuestionnaire",
    "UpdateUbosResponseDataPepQuestionnaireAssociation",
    "UpdateUbosResponseDataPepQuestionnaireDeclarationType",
    "UpdateUbosResponseDataPepQuestionnaireSelf",
    "UpdateUbosResponseDataPepQuestionnaireSelfPepCategory",
]
