# This file was auto-generated by Fern from our API Definition.

import typing

CreateSourceWalletAddressesResponseDataItemRiskLevel = typing.Union[
    typing.Literal["low", "medium", "high", "critical"], typing.Any
]
