# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .create_source_wallet_addresses_response_data_item_chain import CreateSourceWalletAddressesResponseDataItemChain
from .create_source_wallet_addresses_response_data_item_owner_type import (
    CreateSourceWalletAddressesResponseDataItemOwnerType,
)
from .create_source_wallet_addresses_response_data_item_risk_level import (
    CreateSourceWalletAddressesResponseDataItemRiskLevel,
)


class CreateSourceWalletAddressesResponseDataItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the source address
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Version number of the source address record
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the source address was created"),
    ] = None
    """
    Timestamp when the source address was created
    """

    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the source address was last updated"),
    ] = None
    """
    Timestamp when the source address was last updated
    """

    address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The blockchain address
    """

    chain: typing.Optional[CreateSourceWalletAddressesResponseDataItemChain] = pydantic.Field(default=None)
    """
    The blockchain network
    """

    owner_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ownerId"),
        pydantic.Field(alias="ownerId", description="Identifier of the address owner (merchant or sender)"),
    ] = None
    """
    Identifier of the address owner (merchant or sender)
    """

    owner_type: typing_extensions.Annotated[
        typing.Optional[CreateSourceWalletAddressesResponseDataItemOwnerType],
        FieldMetadata(alias="ownerType"),
        pydantic.Field(alias="ownerType", description="Type of the address owner"),
    ] = None
    """
    Type of the address owner
    """

    risk_level: typing_extensions.Annotated[
        typing.Optional[CreateSourceWalletAddressesResponseDataItemRiskLevel],
        FieldMetadata(alias="riskLevel"),
        pydantic.Field(alias="riskLevel", description="Risk assessment level of the address"),
    ] = None
    """
    Risk assessment level of the address
    """

    merchant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="merchantId"),
        pydantic.Field(alias="merchantId", description="Identifier of the merchant associated with this address"),
    ] = None
    """
    Identifier of the merchant associated with this address
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
