# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.beneficiary_relationship import BeneficiaryRelationship
from ...types.purpose import Purpose
from ...types.source_of_funds import SourceOfFunds


class CreateOrdersResponseData(UniversalBaseModel):
    id: typing.Optional[str] = None
    sender_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="senderId"), pydantic.Field(alias="senderId")
    ] = None
    payment_method_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="paymentMethodId"), pydantic.Field(alias="paymentMethodId")
    ] = None
    beneficiary_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="beneficiaryId"), pydantic.Field(alias="beneficiaryId")
    ] = None
    merchant_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="merchantId"), pydantic.Field(alias="merchantId")
    ] = None
    accepted_quote_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="acceptedQuoteId"), pydantic.Field(alias="acceptedQuoteId")
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current status of the order
    """

    purpose: typing.Optional[Purpose] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    beneficiary_relationship: typing_extensions.Annotated[
        typing.Optional[BeneficiaryRelationship],
        FieldMetadata(alias="beneficiaryRelationship"),
        pydantic.Field(alias="beneficiaryRelationship"),
    ] = None
    source_of_funds: typing_extensions.Annotated[
        typing.Optional[SourceOfFunds], FieldMetadata(alias="sourceOfFunds"), pydantic.Field(alias="sourceOfFunds")
    ] = None
    customer_reference_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerReferenceId"), pydantic.Field(alias="customerReferenceId")
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ] = None
    uetr: typing.Optional[str] = pydantic.Field(default=None)
    """
    SWIFT Universal End-to-End Transaction Reference for tracking wire transfers
    """

    imad: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fedwire Input Message Accountability Data for tracking domestic wire transfers
    """

    rejection_remarks: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="rejectionRemarks"),
        pydantic.Field(alias="rejectionRemarks", description="Reason for order rejection, if the order was declined"),
    ] = None
    """
    Reason for order rejection, if the order was declined
    """

    disbursement_blockchain_hash: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="disbursementBlockchainHash"),
        pydantic.Field(
            alias="disbursementBlockchainHash", description="Blockchain transaction hash for crypto disbursements"
        ),
    ] = None
    """
    Blockchain transaction hash for crypto disbursements
    """

    payment_processing_partner: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paymentProcessingPartner"),
        pydantic.Field(
            alias="paymentProcessingPartner", description="Name of the payment processing partner used for disbursement"
        ),
    ] = None
    """
    Name of the payment processing partner used for disbursement
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
