# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawFiatDepositsClient, RawFiatDepositsClient
from .types.get_fiat_deposits_response import GetFiatDepositsResponse
from .types.list_fiat_deposits_request_currency import ListFiatDepositsRequestCurrency
from .types.list_fiat_deposits_request_sort_by import ListFiatDepositsRequestSortBy
from .types.list_fiat_deposits_request_sort_order import ListFiatDepositsRequestSortOrder
from .types.list_fiat_deposits_response import ListFiatDepositsResponse


class FiatDepositsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFiatDepositsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFiatDepositsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFiatDepositsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ListFiatDepositsRequestSortBy] = None,
        sort_order: typing.Optional[ListFiatDepositsRequestSortOrder] = None,
        search: typing.Optional[str] = None,
        currency: typing.Optional[ListFiatDepositsRequestCurrency] = None,
        merchant_id: typing.Optional[str] = None,
        sender_id: typing.Optional[str] = None,
        deposit_bank_account_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFiatDepositsResponse:
        """
        Retrieve a paginated list of fiat deposits for a merchant. Only completed deposits are returned. Supports filtering by currency, sender, and deposit bank account.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (0-indexed)

        page_size : typing.Optional[int]
            Number of records per page

        sort_by : typing.Optional[ListFiatDepositsRequestSortBy]
            Sort column

        sort_order : typing.Optional[ListFiatDepositsRequestSortOrder]
            Sort order

        search : typing.Optional[str]
            Search query

        currency : typing.Optional[ListFiatDepositsRequestCurrency]
            Filter by fiat currency

        merchant_id : typing.Optional[str]
            Filter by merchant ID

        sender_id : typing.Optional[str]
            Filter by sender ID

        deposit_bank_account_id : typing.Optional[str]
            Filter by deposit bank account ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFiatDepositsResponse
            Fiat deposits retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.merchants.fiat_deposits.list(
            search="abc123",
            merchant_id="550e8400-e29b-41d4-a716-446655440000",
            sender_id="550e8400-e29b-41d4-a716-446655440001",
            deposit_bank_account_id="550e8400-e29b-41d4-a716-446655440002",
        )
        """
        _response = self._raw_client.list(
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            currency=currency,
            merchant_id=merchant_id,
            sender_id=sender_id,
            deposit_bank_account_id=deposit_bank_account_id,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetFiatDepositsResponse:
        """
        Retrieve a specific fiat deposit by its ID.

        Parameters
        ----------
        id : str
            Fiat deposit ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFiatDepositsResponse
            Fiat deposit retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.merchants.fiat_deposits.get(
            id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncFiatDepositsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFiatDepositsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFiatDepositsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFiatDepositsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ListFiatDepositsRequestSortBy] = None,
        sort_order: typing.Optional[ListFiatDepositsRequestSortOrder] = None,
        search: typing.Optional[str] = None,
        currency: typing.Optional[ListFiatDepositsRequestCurrency] = None,
        merchant_id: typing.Optional[str] = None,
        sender_id: typing.Optional[str] = None,
        deposit_bank_account_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFiatDepositsResponse:
        """
        Retrieve a paginated list of fiat deposits for a merchant. Only completed deposits are returned. Supports filtering by currency, sender, and deposit bank account.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (0-indexed)

        page_size : typing.Optional[int]
            Number of records per page

        sort_by : typing.Optional[ListFiatDepositsRequestSortBy]
            Sort column

        sort_order : typing.Optional[ListFiatDepositsRequestSortOrder]
            Sort order

        search : typing.Optional[str]
            Search query

        currency : typing.Optional[ListFiatDepositsRequestCurrency]
            Filter by fiat currency

        merchant_id : typing.Optional[str]
            Filter by merchant ID

        sender_id : typing.Optional[str]
            Filter by sender ID

        deposit_bank_account_id : typing.Optional[str]
            Filter by deposit bank account ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFiatDepositsResponse
            Fiat deposits retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.merchants.fiat_deposits.list(
                search="abc123",
                merchant_id="550e8400-e29b-41d4-a716-446655440000",
                sender_id="550e8400-e29b-41d4-a716-446655440001",
                deposit_bank_account_id="550e8400-e29b-41d4-a716-446655440002",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            currency=currency,
            merchant_id=merchant_id,
            sender_id=sender_id,
            deposit_bank_account_id=deposit_bank_account_id,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetFiatDepositsResponse:
        """
        Retrieve a specific fiat deposit by its ID.

        Parameters
        ----------
        id : str
            Fiat deposit ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetFiatDepositsResponse
            Fiat deposit retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.merchants.fiat_deposits.get(
                id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
