# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GenerateLedgerAccountsSendersResponseDataAccount(UniversalBaseModel):
    """
    The primary ledger account
    """

    id: typing.Optional[str] = None
    merchant_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="merchantId"), pydantic.Field(alias="merchantId")
    ] = None
    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Account currency
    """

    provider: typing.Optional[str] = pydantic.Field(default=None)
    """
    Account provider
    """

    balance: typing.Optional[float] = pydantic.Field(default=None)
    """
    Current account balance
    """

    owner_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ownerType"),
        pydantic.Field(alias="ownerType", description="Type of account owner"),
    ] = None
    """
    Type of account owner
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
