# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .generate_ledger_accounts_senders_response_data_account import GenerateLedgerAccountsSendersResponseDataAccount
from .generate_ledger_accounts_senders_response_data_virtual_accounts_item import (
    GenerateLedgerAccountsSendersResponseDataVirtualAccountsItem,
)


class GenerateLedgerAccountsSendersResponseData(UniversalBaseModel):
    account: typing.Optional[GenerateLedgerAccountsSendersResponseDataAccount] = pydantic.Field(default=None)
    """
    The primary ledger account
    """

    virtual_accounts: typing_extensions.Annotated[
        typing.Optional[typing.List[GenerateLedgerAccountsSendersResponseDataVirtualAccountsItem]],
        FieldMetadata(alias="virtualAccounts"),
        pydantic.Field(alias="virtualAccounts", description="List of virtual bank accounts created"),
    ] = None
    """
    List of virtual bank accounts created
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
