# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetMerchantsResponseDataAddress(UniversalBaseModel):
    """
    Merchant's business address information
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the address
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Version number of the address record
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the address was created"),
    ] = None
    """
    Timestamp when the address was created
    """

    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the address was last updated"),
    ] = None
    """
    Timestamp when the address was last updated
    """

    street: typing.Optional[str] = pydantic.Field(default=None)
    """
    Street address line 1
    """

    street2: typing.Optional[str] = pydantic.Field(default=None)
    """
    Street address line 2
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City name
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State/province code
    """

    postal_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="postalCode"),
        pydantic.Field(alias="postalCode", description="Postal/ZIP code"),
    ] = None
    """
    Postal/ZIP code
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Two-letter ISO country code
    """

    merchant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="merchantId"),
        pydantic.Field(alias="merchantId", description="Reference to the merchant"),
    ] = None
    """
    Reference to the merchant
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
