# This file was auto-generated by Fern from our API Definition.

import typing

CreateV3BeneficiariesResponseDataIdentityDocumentType = typing.Union[
    typing.Literal["PASSPORT", "DRIVER_LICENSE", "NATIONAL_ID", "ID_CARD", "RESIDENT_CARD", "VOTER_ID_CARD", "TAX_ID"],
    typing.Any,
]
