# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_v1beneficiaries_response_data_verification_status import GetV1BeneficiariesResponseDataVerificationStatus


class GetV1BeneficiariesResponseDataVerification(UniversalBaseModel):
    """
    Verification information
    """

    status: typing.Optional[GetV1BeneficiariesResponseDataVerificationStatus] = pydantic.Field(default=None)
    """
    Verification status
    """

    status_updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="statusUpdatedAt"),
        pydantic.Field(alias="statusUpdatedAt", description="Timestamp of the last verification status update"),
    ] = None
    """
    Timestamp of the last verification status update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
