# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.payment_method_type import PaymentMethodType
from .get_v1beneficiaries_response_data_address import GetV1BeneficiariesResponseDataAddress
from .get_v1beneficiaries_response_data_business_type import GetV1BeneficiariesResponseDataBusinessType
from .get_v1beneficiaries_response_data_identity import GetV1BeneficiariesResponseDataIdentity
from .get_v1beneficiaries_response_data_payment_info import GetV1BeneficiariesResponseDataPaymentInfo
from .get_v1beneficiaries_response_data_status import GetV1BeneficiariesResponseDataStatus
from .get_v1beneficiaries_response_data_type import GetV1BeneficiariesResponseDataType
from .get_v1beneficiaries_response_data_verification import GetV1BeneficiariesResponseDataVerification


class GetV1BeneficiariesResponseData(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the beneficiary
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Version number of the beneficiary record
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the beneficiary was created"),
    ] = None
    """
    Timestamp when the beneficiary was created
    """

    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the beneficiary was last updated"),
    ] = None
    """
    Timestamp when the beneficiary was last updated
    """

    type: typing.Optional[GetV1BeneficiariesResponseDataType] = pydantic.Field(default=None)
    """
    Type of beneficiary
    """

    first_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="firstName"),
        pydantic.Field(alias="firstName", description="First name (for individual beneficiaries)"),
    ] = None
    """
    First name (for individual beneficiaries)
    """

    last_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastName"),
        pydantic.Field(alias="lastName", description="Last name (for individual beneficiaries)"),
    ] = None
    """
    Last name (for individual beneficiaries)
    """

    middle_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="middleName"),
        pydantic.Field(alias="middleName", description="Middle name (for individual beneficiaries)"),
    ] = None
    """
    Middle name (for individual beneficiaries)
    """

    full_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fullName"),
        pydantic.Field(alias="fullName", description="Full name of the business or individual"),
    ] = None
    """
    Full name of the business or individual
    """

    birth_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="birthDate"),
        pydantic.Field(alias="birthDate", description="Date of birth (for individual beneficiaries)"),
    ] = None
    """
    Date of birth (for individual beneficiaries)
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number in E.164 format
    """

    address: typing.Optional[GetV1BeneficiariesResponseDataAddress] = pydantic.Field(default=None)
    """
    Address information
    """

    merchant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="merchantId"),
        pydantic.Field(alias="merchantId", description="Identifier of the associated merchant"),
    ] = None
    """
    Identifier of the associated merchant
    """

    verification: typing.Optional[GetV1BeneficiariesResponseDataVerification] = pydantic.Field(default=None)
    """
    Verification information
    """

    status: typing.Optional[GetV1BeneficiariesResponseDataStatus] = pydantic.Field(default=None)
    """
    Indicates whether the beneficiary is currently active or inactive.
    """

    payment_type: typing_extensions.Annotated[
        typing.Optional[PaymentMethodType], FieldMetadata(alias="paymentType"), pydantic.Field(alias="paymentType")
    ] = None
    payment_info: typing_extensions.Annotated[
        typing.Optional[GetV1BeneficiariesResponseDataPaymentInfo],
        FieldMetadata(alias="paymentInfo"),
        pydantic.Field(alias="paymentInfo", description="Payment method details"),
    ] = None
    """
    Payment method details
    """

    identity: typing.Optional[GetV1BeneficiariesResponseDataIdentity] = pydantic.Field(default=None)
    """
    Identity document information (required for certain countries)
    """

    business_type: typing_extensions.Annotated[
        typing.Optional[GetV1BeneficiariesResponseDataBusinessType],
        FieldMetadata(alias="businessType"),
        pydantic.Field(alias="businessType", description="Type of business entity (for business beneficiaries)"),
    ] = None
    """
    Type of business entity (for business beneficiaries)
    """

    business_registration_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="businessRegistrationNumber"),
        pydantic.Field(alias="businessRegistrationNumber", description="Business registration number"),
    ] = None
    """
    Business registration number
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Custom key-value metadata attached to this beneficiary
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
