# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .merchant_login_auth_response_data_user import MerchantLoginAuthResponseDataUser


class MerchantLoginAuthResponseData(UniversalBaseModel):
    access_token: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="accessToken"),
        pydantic.Field(alias="accessToken", description="JWT access token for API authorization"),
    ] = None
    """
    JWT access token for API authorization
    """

    refresh_token: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="refreshToken"),
        pydantic.Field(alias="refreshToken", description="Token used to obtain a new access token"),
    ] = None
    """
    Token used to obtain a new access token
    """

    user: typing.Optional[MerchantLoginAuthResponseDataUser] = pydantic.Field(default=None)
    """
    Authenticated user details
    """

    qr_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="qrCode"),
        pydantic.Field(
            alias="qrCode",
            description="QR code data URL for MFA setup (only returned on first login when MFA is not yet configured)",
        ),
    ] = None
    """
    QR code data URL for MFA setup (only returned on first login when MFA is not yet configured)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
