
import typing

UpdateWebhooksResponseDataEventsItem = typing.Union[
    typing.Literal[
        "order:*",
        "order:created",
        "order:awaiting_funds",
        "order:awaiting_funds_timeout",
        "order:funds_received",
        "order:in_progress",
        "order:sent_to_beneficiary",
        "order:success",
        "order:failed",
        "order:cancelled",
        "order:returned",
        "order:proof_of_payment_received",
        "order:invoice_review_required",
        "sender:*",
        "sender:created",
        "sender:kyb_pending",
        "sender:kyb_approved",
        "sender:kyb_declined",
        "sender:kyc_pending",
        "sender:kyc_approved",
        "sender:kyc_declined",
        "sender:tos_link_generated",
        "sender:tos_accepted",
        "sender:activated",
        "sender:deactivated",
        "ubo:*",
        "ubo:created",
        "ubo:verification_pending",
        "ubo:verification_approved",
        "ubo:verification_declined",
        "beneficiary:*",
        "beneficiary:created",
        "beneficiary:verification_approved",
        "beneficiary:verification_declined",
        "fiat_deposit:settled",
        "stablecoin_deposit:settled",
        "stablecoin_deposit:rejected",
    ],
    typing.Any,
]
