# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawSendersClient, RawSendersClient
from .types.get_ubo_rules_v1senders_request_owner_type import GetUboRulesV1SendersRequestOwnerType
from .types.get_ubo_rules_v1senders_response import GetUboRulesV1SendersResponse
from .types.get_ubo_rules_v2senders_request_owner_type import GetUboRulesV2SendersRequestOwnerType
from .types.get_ubo_rules_v2senders_response import GetUboRulesV2SendersResponse
from .types.get_v1senders_request_owner_type import GetV1SendersRequestOwnerType
from .types.get_v1senders_response import GetV1SendersResponse
from .types.get_v2senders_request_owner_type import GetV2SendersRequestOwnerType
from .types.get_v2senders_response import GetV2SendersResponse
from .types.list_countries_senders_response import ListCountriesSendersResponse
from .types.list_document_types_v1senders_request_owner_type import ListDocumentTypesV1SendersRequestOwnerType
from .types.list_document_types_v1senders_response import ListDocumentTypesV1SendersResponse
from .types.list_document_types_v2senders_request_owner_type import ListDocumentTypesV2SendersRequestOwnerType
from .types.list_document_types_v2senders_response import ListDocumentTypesV2SendersResponse


class SendersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSendersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSendersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSendersClient
        """
        return self._raw_client

    def get_v1(
        self,
        *,
        owner_type: GetV1SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetV1SendersResponse:
        """
        Retrieves all validation rules required for creating a sender in a specific country. Use these rules to validate sender information before submission.

        Parameters
        ----------
        owner_type : GetV1SendersRequestOwnerType
            Type of sender entity (individual or business)

        country : str
            Two-letter ISO country code (e.g., IN for India)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetV1SendersResponse
            Sender validation rules retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.get_v1(
            owner_type="individual",
            country="country",
        )
        """
        _response = self._raw_client.get_v1(owner_type=owner_type, country=country, request_options=request_options)
        return _response.data

    def get_ubo_rules_v1(
        self,
        *,
        owner_type: GetUboRulesV1SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetUboRulesV1SendersResponse:
        """
        Retrieves validation rules for UBO information based on country and owner type. These rules specify all required fields for UBO verification.

        Parameters
        ----------
        owner_type : GetUboRulesV1SendersRequestOwnerType
            Type of sender entity

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUboRulesV1SendersResponse
            UBO validation rules retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.get_ubo_rules_v1(
            owner_type="individual",
            country="country",
        )
        """
        _response = self._raw_client.get_ubo_rules_v1(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    def list_document_types_v1(
        self,
        *,
        owner_type: ListDocumentTypesV1SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListDocumentTypesV1SendersResponse:
        """
        Retrieves the list of required documents for sender verification. This includes business registration documents and identity proofs.

        Parameters
        ----------
        owner_type : ListDocumentTypesV1SendersRequestOwnerType
            Type of sender entity

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListDocumentTypesV1SendersResponse
            Required document types retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.list_document_types_v1(
            owner_type="individual",
            country="country",
        )
        """
        _response = self._raw_client.list_document_types_v1(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    def get_v2(
        self,
        *,
        owner_type: GetV2SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetV2SendersResponse:
        """
        Retrieves all validation rules required for creating a sender in a specific country. V2 adds structured `supportedDocumentTypes` on identity fields, indicating which document types are available per country and their file upload requirements. The `documentNumber`, `documentFront`, and `documentBack` nested fields are removed as their requirements are conveyed by `supportedDocumentTypes`.

        Parameters
        ----------
        owner_type : GetV2SendersRequestOwnerType
            Type of sender entity (individual or business)

        country : str
            Two-letter ISO country code (e.g., IN for India)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetV2SendersResponse
            Sender validation rules retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.get_v2(
            owner_type="individual",
            country="country",
        )
        """
        _response = self._raw_client.get_v2(owner_type=owner_type, country=country, request_options=request_options)
        return _response.data

    def get_ubo_rules_v2(
        self,
        *,
        owner_type: GetUboRulesV2SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetUboRulesV2SendersResponse:
        """
        Retrieves validation rules for UBO (Ultimate Beneficial Owner) information. V2 adds structured `supportedDocumentTypes` on the identity documentType field, indicating available document types per country and their file upload requirements.

        Parameters
        ----------
        owner_type : GetUboRulesV2SendersRequestOwnerType
            Type of sender entity (must be business for UBO rules)

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUboRulesV2SendersResponse
            UBO validation rules retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.get_ubo_rules_v2(
            owner_type="business",
            country="country",
        )
        """
        _response = self._raw_client.get_ubo_rules_v2(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    def list_document_types_v2(
        self,
        *,
        owner_type: ListDocumentTypesV2SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListDocumentTypesV2SendersResponse:
        """
        Retrieves the list of required documents for sender verification. This includes business registration documents and identity proofs. Same as V1.

        Parameters
        ----------
        owner_type : ListDocumentTypesV2SendersRequestOwnerType
            Type of sender entity

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListDocumentTypesV2SendersResponse
            Required document types retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.list_document_types_v2(
            owner_type="individual",
            country="country",
        )
        """
        _response = self._raw_client.list_document_types_v2(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    def list_countries(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListCountriesSendersResponse:
        """
        Retrieve a list of countries from which senders can originate payments.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCountriesSendersResponse
            List of supported sender countries

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.validation_rules.senders.list_countries()
        """
        _response = self._raw_client.list_countries(request_options=request_options)
        return _response.data


class AsyncSendersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSendersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSendersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSendersClient
        """
        return self._raw_client

    async def get_v1(
        self,
        *,
        owner_type: GetV1SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetV1SendersResponse:
        """
        Retrieves all validation rules required for creating a sender in a specific country. Use these rules to validate sender information before submission.

        Parameters
        ----------
        owner_type : GetV1SendersRequestOwnerType
            Type of sender entity (individual or business)

        country : str
            Two-letter ISO country code (e.g., IN for India)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetV1SendersResponse
            Sender validation rules retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.get_v1(
                owner_type="individual",
                country="country",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_v1(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    async def get_ubo_rules_v1(
        self,
        *,
        owner_type: GetUboRulesV1SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetUboRulesV1SendersResponse:
        """
        Retrieves validation rules for UBO information based on country and owner type. These rules specify all required fields for UBO verification.

        Parameters
        ----------
        owner_type : GetUboRulesV1SendersRequestOwnerType
            Type of sender entity

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUboRulesV1SendersResponse
            UBO validation rules retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.get_ubo_rules_v1(
                owner_type="individual",
                country="country",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_ubo_rules_v1(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    async def list_document_types_v1(
        self,
        *,
        owner_type: ListDocumentTypesV1SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListDocumentTypesV1SendersResponse:
        """
        Retrieves the list of required documents for sender verification. This includes business registration documents and identity proofs.

        Parameters
        ----------
        owner_type : ListDocumentTypesV1SendersRequestOwnerType
            Type of sender entity

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListDocumentTypesV1SendersResponse
            Required document types retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.list_document_types_v1(
                owner_type="individual",
                country="country",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_document_types_v1(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    async def get_v2(
        self,
        *,
        owner_type: GetV2SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetV2SendersResponse:
        """
        Retrieves all validation rules required for creating a sender in a specific country. V2 adds structured `supportedDocumentTypes` on identity fields, indicating which document types are available per country and their file upload requirements. The `documentNumber`, `documentFront`, and `documentBack` nested fields are removed as their requirements are conveyed by `supportedDocumentTypes`.

        Parameters
        ----------
        owner_type : GetV2SendersRequestOwnerType
            Type of sender entity (individual or business)

        country : str
            Two-letter ISO country code (e.g., IN for India)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetV2SendersResponse
            Sender validation rules retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.get_v2(
                owner_type="individual",
                country="country",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_v2(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    async def get_ubo_rules_v2(
        self,
        *,
        owner_type: GetUboRulesV2SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetUboRulesV2SendersResponse:
        """
        Retrieves validation rules for UBO (Ultimate Beneficial Owner) information. V2 adds structured `supportedDocumentTypes` on the identity documentType field, indicating available document types per country and their file upload requirements.

        Parameters
        ----------
        owner_type : GetUboRulesV2SendersRequestOwnerType
            Type of sender entity (must be business for UBO rules)

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUboRulesV2SendersResponse
            UBO validation rules retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.get_ubo_rules_v2(
                owner_type="business",
                country="country",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_ubo_rules_v2(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    async def list_document_types_v2(
        self,
        *,
        owner_type: ListDocumentTypesV2SendersRequestOwnerType,
        country: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListDocumentTypesV2SendersResponse:
        """
        Retrieves the list of required documents for sender verification. This includes business registration documents and identity proofs. Same as V1.

        Parameters
        ----------
        owner_type : ListDocumentTypesV2SendersRequestOwnerType
            Type of sender entity

        country : str
            Two-letter ISO country code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListDocumentTypesV2SendersResponse
            Required document types retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.list_document_types_v2(
                owner_type="individual",
                country="country",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_document_types_v2(
            owner_type=owner_type, country=country, request_options=request_options
        )
        return _response.data

    async def list_countries(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListCountriesSendersResponse:
        """
        Retrieve a list of countries from which senders can originate payments.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCountriesSendersResponse
            List of supported sender countries

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.validation_rules.senders.list_countries()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_countries(request_options=request_options)
        return _response.data
