# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.bank_account_info import BankAccountInfo
from ...types.crypto_wallet_info import CryptoWalletInfo
from ...types.instapay_info import InstapayInfo
from ...types.mobile_money_info import MobileMoneyInfo
from ...types.pix_info import PixInfo
from ...types.spei_info import SpeiInfo
from ...types.swiftpay_pesonet_info import SwiftpayPesonetInfo

UpdatePaymentMethodRequestData = typing.Union[
    BankAccountInfo, PixInfo, InstapayInfo, SwiftpayPesonetInfo, SpeiInfo, MobileMoneyInfo, CryptoWalletInfo
]
