# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AcceptTermsMerchantsResponse,
        AcceptTermsMerchantsResponseData,
        GetBalancesMerchantsResponse,
        GetBalancesMerchantsResponseDataItem,
        GetMerchantsResponse,
        GetMerchantsResponseData,
        GetMerchantsResponseDataAddress,
        GetMerchantsResponseDataKyb,
        GetMerchantsResponseDataKybStatus,
        GetMerchantsResponseDataStatus,
        GetMerchantsResponseDataUbo,
    )
    from . import accounts, fiat_deposits, source_wallet_addresses, stablecoin_deposits, transactions
    from .accounts import (
        ListAccountsRequestSortBy,
        ListAccountsRequestSortOrder,
        ListAccountsResponse,
        ListAccountsResponseDataItem,
        ListAccountsResponseDataItemCurrency,
        ListBalancesAccountsResponse,
        ListBalancesAccountsResponseDataItem,
        ListSenderBalancesAccountsRequestCurrency,
        ListSenderBalancesAccountsResponse,
        ListSenderBalancesAccountsResponseDataItem,
    )
    from .fiat_deposits import (
        GetFiatDepositsResponse,
        ListFiatDepositsRequestCurrency,
        ListFiatDepositsRequestSortBy,
        ListFiatDepositsRequestSortOrder,
        ListFiatDepositsResponse,
    )
    from .source_wallet_addresses import (
        CreateSourceWalletAddressesResponse,
        CreateSourceWalletAddressesResponseDataItem,
        CreateSourceWalletAddressesResponseDataItemChain,
        CreateSourceWalletAddressesResponseDataItemOwnerType,
        CreateSourceWalletAddressesResponseDataItemRiskLevel,
        ListSourceWalletAddressesResponse,
        ListSourceWalletAddressesResponseDataItem,
        ListSourceWalletAddressesResponseDataItemChain,
        ListSourceWalletAddressesResponseDataItemOwnerType,
        ListSourceWalletAddressesResponseDataItemRiskLevel,
    )
    from .stablecoin_deposits import (
        GetStablecoinDepositsResponse,
        ListStablecoinDepositsRequestCurrency,
        ListStablecoinDepositsRequestSortBy,
        ListStablecoinDepositsRequestSortOrder,
        ListStablecoinDepositsRequestStatus,
        ListStablecoinDepositsRequestSwaRiskLevel,
        ListStablecoinDepositsResponse,
    )
    from .transactions import (
        ListTransactionsRequestSortOrder,
        ListTransactionsResponse,
        ListTransactionsResponseDataItem,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "AcceptTermsMerchantsResponse": ".types",
    "AcceptTermsMerchantsResponseData": ".types",
    "CreateSourceWalletAddressesResponse": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItem": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItemChain": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItemOwnerType": ".source_wallet_addresses",
    "CreateSourceWalletAddressesResponseDataItemRiskLevel": ".source_wallet_addresses",
    "GetBalancesMerchantsResponse": ".types",
    "GetBalancesMerchantsResponseDataItem": ".types",
    "GetFiatDepositsResponse": ".fiat_deposits",
    "GetMerchantsResponse": ".types",
    "GetMerchantsResponseData": ".types",
    "GetMerchantsResponseDataAddress": ".types",
    "GetMerchantsResponseDataKyb": ".types",
    "GetMerchantsResponseDataKybStatus": ".types",
    "GetMerchantsResponseDataStatus": ".types",
    "GetMerchantsResponseDataUbo": ".types",
    "GetStablecoinDepositsResponse": ".stablecoin_deposits",
    "ListAccountsRequestSortBy": ".accounts",
    "ListAccountsRequestSortOrder": ".accounts",
    "ListAccountsResponse": ".accounts",
    "ListAccountsResponseDataItem": ".accounts",
    "ListAccountsResponseDataItemCurrency": ".accounts",
    "ListBalancesAccountsResponse": ".accounts",
    "ListBalancesAccountsResponseDataItem": ".accounts",
    "ListFiatDepositsRequestCurrency": ".fiat_deposits",
    "ListFiatDepositsRequestSortBy": ".fiat_deposits",
    "ListFiatDepositsRequestSortOrder": ".fiat_deposits",
    "ListFiatDepositsResponse": ".fiat_deposits",
    "ListSenderBalancesAccountsRequestCurrency": ".accounts",
    "ListSenderBalancesAccountsResponse": ".accounts",
    "ListSenderBalancesAccountsResponseDataItem": ".accounts",
    "ListSourceWalletAddressesResponse": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItem": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItemChain": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItemOwnerType": ".source_wallet_addresses",
    "ListSourceWalletAddressesResponseDataItemRiskLevel": ".source_wallet_addresses",
    "ListStablecoinDepositsRequestCurrency": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestSortBy": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestSortOrder": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestStatus": ".stablecoin_deposits",
    "ListStablecoinDepositsRequestSwaRiskLevel": ".stablecoin_deposits",
    "ListStablecoinDepositsResponse": ".stablecoin_deposits",
    "ListTransactionsRequestSortOrder": ".transactions",
    "ListTransactionsResponse": ".transactions",
    "ListTransactionsResponseDataItem": ".transactions",
    "accounts": ".accounts",
    "fiat_deposits": ".fiat_deposits",
    "source_wallet_addresses": ".source_wallet_addresses",
    "stablecoin_deposits": ".stablecoin_deposits",
    "transactions": ".transactions",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AcceptTermsMerchantsResponse",
    "AcceptTermsMerchantsResponseData",
    "CreateSourceWalletAddressesResponse",
    "CreateSourceWalletAddressesResponseDataItem",
    "CreateSourceWalletAddressesResponseDataItemChain",
    "CreateSourceWalletAddressesResponseDataItemOwnerType",
    "CreateSourceWalletAddressesResponseDataItemRiskLevel",
    "GetBalancesMerchantsResponse",
    "GetBalancesMerchantsResponseDataItem",
    "GetFiatDepositsResponse",
    "GetMerchantsResponse",
    "GetMerchantsResponseData",
    "GetMerchantsResponseDataAddress",
    "GetMerchantsResponseDataKyb",
    "GetMerchantsResponseDataKybStatus",
    "GetMerchantsResponseDataStatus",
    "GetMerchantsResponseDataUbo",
    "GetStablecoinDepositsResponse",
    "ListAccountsRequestSortBy",
    "ListAccountsRequestSortOrder",
    "ListAccountsResponse",
    "ListAccountsResponseDataItem",
    "ListAccountsResponseDataItemCurrency",
    "ListBalancesAccountsResponse",
    "ListBalancesAccountsResponseDataItem",
    "ListFiatDepositsRequestCurrency",
    "ListFiatDepositsRequestSortBy",
    "ListFiatDepositsRequestSortOrder",
    "ListFiatDepositsResponse",
    "ListSenderBalancesAccountsRequestCurrency",
    "ListSenderBalancesAccountsResponse",
    "ListSenderBalancesAccountsResponseDataItem",
    "ListSourceWalletAddressesResponse",
    "ListSourceWalletAddressesResponseDataItem",
    "ListSourceWalletAddressesResponseDataItemChain",
    "ListSourceWalletAddressesResponseDataItemOwnerType",
    "ListSourceWalletAddressesResponseDataItemRiskLevel",
    "ListStablecoinDepositsRequestCurrency",
    "ListStablecoinDepositsRequestSortBy",
    "ListStablecoinDepositsRequestSortOrder",
    "ListStablecoinDepositsRequestStatus",
    "ListStablecoinDepositsRequestSwaRiskLevel",
    "ListStablecoinDepositsResponse",
    "ListTransactionsRequestSortOrder",
    "ListTransactionsResponse",
    "ListTransactionsResponseDataItem",
    "accounts",
    "fiat_deposits",
    "source_wallet_addresses",
    "stablecoin_deposits",
    "transactions",
]
