# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.beneficiary_relationship import BeneficiaryRelationship
from ..types.order_document_input import OrderDocumentInput
from ..types.purpose import Purpose
from ..types.source_of_funds import SourceOfFunds
from .raw_client import AsyncRawOrdersClient, RawOrdersClient
from .types.cancel_orders_response import CancelOrdersResponse
from .types.create_orders_response import CreateOrdersResponse
from .types.get_deposit_bank_account_orders_response import GetDepositBankAccountOrdersResponse
from .types.get_deposit_wallet_address_orders_response import GetDepositWalletAddressOrdersResponse
from .types.get_orders_response import GetOrdersResponse
from .types.list_events_orders_response import ListEventsOrdersResponse
from .types.list_orders_request_sort_order import ListOrdersRequestSortOrder
from .types.list_orders_request_status import ListOrdersRequestStatus
from .types.list_orders_response import ListOrdersResponse

if typing.TYPE_CHECKING:
    from .documents.client import AsyncDocumentsClient, DocumentsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrdersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._documents: typing.Optional[DocumentsClient] = None

    @property
    def with_raw_response(self) -> RawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrdersClient
        """
        return self._raw_client

    def list(
        self,
        *,
        id: typing.Optional[str] = None,
        source_currency: typing.Optional[str] = None,
        accepted_gross_source_amount: typing.Optional[str] = None,
        sender_id: typing.Optional[str] = None,
        status: typing.Optional[ListOrdersRequestStatus] = None,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        target_currency: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        sort_order: typing.Optional[ListOrdersRequestSortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListOrdersResponse:
        """
        Retrieves a list of orders for the authenticated user, with optional filters to narrow down results based on status, date range, target currency, or other relevant criteria.

        Parameters
        ----------
        id : typing.Optional[str]
            Filter by order ID

        source_currency : typing.Optional[str]
            Filter by source currency

        accepted_gross_source_amount : typing.Optional[str]
            Filter by accepted gross source amount

        sender_id : typing.Optional[str]
            Filter by sender ID

        status : typing.Optional[ListOrdersRequestStatus]
            Filter by order status.

        start_date : typing.Optional[dt.datetime]
            Filter orders starting from this date (ISO8601 format).

        end_date : typing.Optional[dt.datetime]
            Filter orders up to this date (ISO8601 format).

        target_currency : typing.Optional[str]
            Filter by target currency ISO code (e.g., "EUR", "GBP").

        page : typing.Optional[int]
            Pagination page number.

        page_size : typing.Optional[int]
            Number of orders per page.

        sort_by : typing.Optional[str]
            Field to sort the orders by (e.g., "creationDate", "amount").

        sort_order : typing.Optional[ListOrdersRequestSortOrder]
            Sort order (ascending or descending).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListOrdersResponse
            Orders list retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.list()
        """
        _response = self._raw_client.list(
            id=id,
            source_currency=source_currency,
            accepted_gross_source_amount=accepted_gross_source_amount,
            sender_id=sender_id,
            status=status,
            start_date=start_date,
            end_date=end_date,
            target_currency=target_currency,
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    def get(self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetOrdersResponse:
        """
        Retrieves detailed information about a specific order, including its current status and progress.

        Parameters
        ----------
        order_id : str
            Unique identifier for the order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrdersResponse
            Order retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.get(
            order_id="orderId",
        )
        """
        _response = self._raw_client.get(order_id, request_options=request_options)
        return _response.data

    def get_deposit_wallet_address(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetDepositWalletAddressOrdersResponse:
        """
        Retrieves the deposit wallet address for a specific order

        Parameters
        ----------
        order_id : str
            The unique identifier of the order

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDepositWalletAddressOrdersResponse
            Deposit wallet address retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.get_deposit_wallet_address(
            order_id="7f916142-a6ba-45ca-9d7e-ff6f93091efc",
        )
        """
        _response = self._raw_client.get_deposit_wallet_address(order_id, request_options=request_options)
        return _response.data

    def get_deposit_bank_account(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetDepositBankAccountOrdersResponse:
        """
        Retrieves the deposit bank account details for onramp orders. This endpoint provides bank account information where funds should be deposited to complete the order.

        Parameters
        ----------
        order_id : str
            The unique identifier of the order

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDepositBankAccountOrdersResponse
            Deposit bank account details retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.get_deposit_bank_account(
            order_id="orderId",
        )
        """
        _response = self._raw_client.get_deposit_bank_account(order_id, request_options=request_options)
        return _response.data

    def cancel(
        self,
        order_id: str,
        *,
        cancellation_remarks: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelOrdersResponse:
        """
        Cancels an existing order. The order must be in a cancellable state.

        Parameters
        ----------
        order_id : str
            Unique identifier for the order to cancel

        cancellation_remarks : typing.Optional[str]
            Optional remarks or reason for cancelling the order

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelOrdersResponse
            Order cancelled successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.cancel(
            order_id="orderId",
        )
        """
        _response = self._raw_client.cancel(
            order_id, cancellation_remarks=cancellation_remarks, request_options=request_options
        )
        return _response.data

    def create(
        self,
        *,
        sender_id: str,
        payment_method_id: str,
        accepted_quote_id: str,
        purpose: typing.Optional[Purpose] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        beneficiary_relationship: typing.Optional[BeneficiaryRelationship] = OMIT,
        source_of_funds: typing.Optional[SourceOfFunds] = OMIT,
        documents: typing.Optional[typing.Sequence[OrderDocumentInput]] = OMIT,
        customer_reference_id: typing.Optional[str] = OMIT,
        senders_own_funds: typing.Optional[bool] = OMIT,
        use_pooled_funds: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateOrdersResponse:
        """
        Create a new order using a payment method ID. This is the recommended way to create orders. Requires an accepted quote, a sender, and a payment method.

        Parameters
        ----------
        sender_id : str
            ID of the sender initiating the order

        payment_method_id : str
            ID of the payment method to use for delivery

        accepted_quote_id : str
            ID of the accepted quote

        purpose : typing.Optional[Purpose]
            Purpose of payment for the order. Required if the beneficiary does not have a purpose of payment configured during onboarding.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata to attach to the order

        beneficiary_relationship : typing.Optional[BeneficiaryRelationship]
            Beneficiary relationship for the order. Required if the beneficiary does not have a beneficiary relationship configured during onboarding.

        source_of_funds : typing.Optional[SourceOfFunds]
            Source of funds for the order. Required if the sender does not have a source of funds configured during onboarding.

        documents : typing.Optional[typing.Sequence[OrderDocumentInput]]
            Supporting documents for the order. Required if the beneficiary does not have a purpose of payment document on file.

        customer_reference_id : typing.Optional[str]
            Your internal reference ID for this order

        senders_own_funds : typing.Optional[bool]
            Declaration that the funds belong to the sender.

        use_pooled_funds : typing.Optional[bool]
            Optional. When true, the order is funded from your pooled merchant account balance instead of the sender’s individual wallet. The order still belongs to the sender and the payout runs in the sender’s name — only the funding source changes. Supported for stablecoin-source orders. Pooled Merchant Accounts is available to select merchants only — please reach out to Mesta support to have it enabled for your account.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOrdersResponse
            Order created successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.create(
            sender_id="550e8400-e29b-41d4-a716-446655440001",
            payment_method_id="550e8400-e29b-41d4-a716-446655440002",
            accepted_quote_id="550e8400-e29b-41d4-a716-446655440003",
        )
        """
        _response = self._raw_client.create(
            sender_id=sender_id,
            payment_method_id=payment_method_id,
            accepted_quote_id=accepted_quote_id,
            purpose=purpose,
            metadata=metadata,
            beneficiary_relationship=beneficiary_relationship,
            source_of_funds=source_of_funds,
            documents=documents,
            customer_reference_id=customer_reference_id,
            senders_own_funds=senders_own_funds,
            use_pooled_funds=use_pooled_funds,
            request_options=request_options,
        )
        return _response.data

    def list_events(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListEventsOrdersResponse:
        """
        Retrieve the event history for a specific order. Returns a chronological list of state transitions and their timestamps.

        Parameters
        ----------
        order_id : str
            Order ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEventsOrdersResponse
            List of order events

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.orders.list_events(
            order_id="orderId",
        )
        """
        _response = self._raw_client.list_events(order_id, request_options=request_options)
        return _response.data

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import DocumentsClient  # noqa: E402

            self._documents = DocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents


class AsyncOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrdersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._documents: typing.Optional[AsyncDocumentsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrdersClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        id: typing.Optional[str] = None,
        source_currency: typing.Optional[str] = None,
        accepted_gross_source_amount: typing.Optional[str] = None,
        sender_id: typing.Optional[str] = None,
        status: typing.Optional[ListOrdersRequestStatus] = None,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        target_currency: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        sort_order: typing.Optional[ListOrdersRequestSortOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListOrdersResponse:
        """
        Retrieves a list of orders for the authenticated user, with optional filters to narrow down results based on status, date range, target currency, or other relevant criteria.

        Parameters
        ----------
        id : typing.Optional[str]
            Filter by order ID

        source_currency : typing.Optional[str]
            Filter by source currency

        accepted_gross_source_amount : typing.Optional[str]
            Filter by accepted gross source amount

        sender_id : typing.Optional[str]
            Filter by sender ID

        status : typing.Optional[ListOrdersRequestStatus]
            Filter by order status.

        start_date : typing.Optional[dt.datetime]
            Filter orders starting from this date (ISO8601 format).

        end_date : typing.Optional[dt.datetime]
            Filter orders up to this date (ISO8601 format).

        target_currency : typing.Optional[str]
            Filter by target currency ISO code (e.g., "EUR", "GBP").

        page : typing.Optional[int]
            Pagination page number.

        page_size : typing.Optional[int]
            Number of orders per page.

        sort_by : typing.Optional[str]
            Field to sort the orders by (e.g., "creationDate", "amount").

        sort_order : typing.Optional[ListOrdersRequestSortOrder]
            Sort order (ascending or descending).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListOrdersResponse
            Orders list retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            id=id,
            source_currency=source_currency,
            accepted_gross_source_amount=accepted_gross_source_amount,
            sender_id=sender_id,
            status=status,
            start_date=start_date,
            end_date=end_date,
            target_currency=target_currency,
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    async def get(self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetOrdersResponse:
        """
        Retrieves detailed information about a specific order, including its current status and progress.

        Parameters
        ----------
        order_id : str
            Unique identifier for the order.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrdersResponse
            Order retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.get(
                order_id="orderId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(order_id, request_options=request_options)
        return _response.data

    async def get_deposit_wallet_address(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetDepositWalletAddressOrdersResponse:
        """
        Retrieves the deposit wallet address for a specific order

        Parameters
        ----------
        order_id : str
            The unique identifier of the order

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDepositWalletAddressOrdersResponse
            Deposit wallet address retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.get_deposit_wallet_address(
                order_id="7f916142-a6ba-45ca-9d7e-ff6f93091efc",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_deposit_wallet_address(order_id, request_options=request_options)
        return _response.data

    async def get_deposit_bank_account(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetDepositBankAccountOrdersResponse:
        """
        Retrieves the deposit bank account details for onramp orders. This endpoint provides bank account information where funds should be deposited to complete the order.

        Parameters
        ----------
        order_id : str
            The unique identifier of the order

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetDepositBankAccountOrdersResponse
            Deposit bank account details retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.get_deposit_bank_account(
                order_id="orderId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_deposit_bank_account(order_id, request_options=request_options)
        return _response.data

    async def cancel(
        self,
        order_id: str,
        *,
        cancellation_remarks: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelOrdersResponse:
        """
        Cancels an existing order. The order must be in a cancellable state.

        Parameters
        ----------
        order_id : str
            Unique identifier for the order to cancel

        cancellation_remarks : typing.Optional[str]
            Optional remarks or reason for cancelling the order

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelOrdersResponse
            Order cancelled successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.cancel(
                order_id="orderId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(
            order_id, cancellation_remarks=cancellation_remarks, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        sender_id: str,
        payment_method_id: str,
        accepted_quote_id: str,
        purpose: typing.Optional[Purpose] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        beneficiary_relationship: typing.Optional[BeneficiaryRelationship] = OMIT,
        source_of_funds: typing.Optional[SourceOfFunds] = OMIT,
        documents: typing.Optional[typing.Sequence[OrderDocumentInput]] = OMIT,
        customer_reference_id: typing.Optional[str] = OMIT,
        senders_own_funds: typing.Optional[bool] = OMIT,
        use_pooled_funds: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateOrdersResponse:
        """
        Create a new order using a payment method ID. This is the recommended way to create orders. Requires an accepted quote, a sender, and a payment method.

        Parameters
        ----------
        sender_id : str
            ID of the sender initiating the order

        payment_method_id : str
            ID of the payment method to use for delivery

        accepted_quote_id : str
            ID of the accepted quote

        purpose : typing.Optional[Purpose]
            Purpose of payment for the order. Required if the beneficiary does not have a purpose of payment configured during onboarding.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Custom metadata to attach to the order

        beneficiary_relationship : typing.Optional[BeneficiaryRelationship]
            Beneficiary relationship for the order. Required if the beneficiary does not have a beneficiary relationship configured during onboarding.

        source_of_funds : typing.Optional[SourceOfFunds]
            Source of funds for the order. Required if the sender does not have a source of funds configured during onboarding.

        documents : typing.Optional[typing.Sequence[OrderDocumentInput]]
            Supporting documents for the order. Required if the beneficiary does not have a purpose of payment document on file.

        customer_reference_id : typing.Optional[str]
            Your internal reference ID for this order

        senders_own_funds : typing.Optional[bool]
            Declaration that the funds belong to the sender.

        use_pooled_funds : typing.Optional[bool]
            Optional. When true, the order is funded from your pooled merchant account balance instead of the sender’s individual wallet. The order still belongs to the sender and the payout runs in the sender’s name — only the funding source changes. Supported for stablecoin-source orders. Pooled Merchant Accounts is available to select merchants only — please reach out to Mesta support to have it enabled for your account.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOrdersResponse
            Order created successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.create(
                sender_id="550e8400-e29b-41d4-a716-446655440001",
                payment_method_id="550e8400-e29b-41d4-a716-446655440002",
                accepted_quote_id="550e8400-e29b-41d4-a716-446655440003",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            sender_id=sender_id,
            payment_method_id=payment_method_id,
            accepted_quote_id=accepted_quote_id,
            purpose=purpose,
            metadata=metadata,
            beneficiary_relationship=beneficiary_relationship,
            source_of_funds=source_of_funds,
            documents=documents,
            customer_reference_id=customer_reference_id,
            senders_own_funds=senders_own_funds,
            use_pooled_funds=use_pooled_funds,
            request_options=request_options,
        )
        return _response.data

    async def list_events(
        self, order_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListEventsOrdersResponse:
        """
        Retrieve the event history for a specific order. Returns a chronological list of state transitions and their timestamps.

        Parameters
        ----------
        order_id : str
            Order ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEventsOrdersResponse
            List of order events

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.list_events(
                order_id="orderId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_events(order_id, request_options=request_options)
        return _response.data

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import AsyncDocumentsClient  # noqa: E402

            self._documents = AsyncDocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents
