
# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        GetUboRulesV1SendersRequestOwnerType,
        GetUboRulesV1SendersResponse,
        GetUboRulesV1SendersResponseData,
        GetUboRulesV1SendersResponseDataOwner,
        GetUboRulesV1SendersResponseDataOwnerType,
        GetUboRulesV1SendersResponseDataRules,
        GetUboRulesV1SendersResponseDataRulesUbo,
        GetUboRulesV2SendersRequestOwnerType,
        GetUboRulesV2SendersResponse,
        GetUboRulesV2SendersResponseData,
        GetUboRulesV2SendersResponseDataOwner,
        GetUboRulesV2SendersResponseDataOwnerType,
        GetUboRulesV2SendersResponseDataRules,
        GetUboRulesV2SendersResponseDataRulesUbo,
        GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItem,
        GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem,
        GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem,
        GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory,
        GetV1SendersRequestOwnerType,
        GetV1SendersResponse,
        GetV1SendersResponseData,
        GetV1SendersResponseDataOwner,
        GetV1SendersResponseDataOwnerType,
        GetV1SendersResponseDataRules,
        GetV1SendersResponseDataRulesRequiredDocumentsItem,
        GetV1SendersResponseDataRulesRequiredDocumentsItemType,
        GetV1SendersResponseDataRulesUbo,
        GetV2SendersRequestOwnerType,
        GetV2SendersResponse,
        GetV2SendersResponseData,
        GetV2SendersResponseDataOwner,
        GetV2SendersResponseDataOwnerType,
        GetV2SendersResponseDataRules,
        GetV2SendersResponseDataRulesRequiredDocumentsItem,
        GetV2SendersResponseDataRulesRequiredDocumentsItemType,
        GetV2SendersResponseDataRulesRequiredFieldsItem,
        GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItem,
        GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem,
        GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory,
        GetV2SendersResponseDataRulesUbo,
        GetV2SendersResponseDataRulesUboRequiredFieldsItem,
        GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem,
        GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem,
        GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory,
        ListCountriesSendersResponse,
        ListDocumentTypesV1SendersRequestOwnerType,
        ListDocumentTypesV1SendersResponse,
        ListDocumentTypesV1SendersResponseData,
        ListDocumentTypesV1SendersResponseDataOwner,
        ListDocumentTypesV1SendersResponseDataOwnerType,
        ListDocumentTypesV1SendersResponseDataRules,
        ListDocumentTypesV1SendersResponseDataRulesRequiredDocumentsItem,
        ListDocumentTypesV1SendersResponseDataRulesRequiredDocumentsItemType,
        ListDocumentTypesV2SendersRequestOwnerType,
        ListDocumentTypesV2SendersResponse,
        ListDocumentTypesV2SendersResponseData,
        ListDocumentTypesV2SendersResponseDataOwner,
        ListDocumentTypesV2SendersResponseDataOwnerType,
        ListDocumentTypesV2SendersResponseDataRules,
        ListDocumentTypesV2SendersResponseDataRulesRequiredDocumentsItem,
        ListDocumentTypesV2SendersResponseDataRulesRequiredDocumentsItemType,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "GetUboRulesV1SendersRequestOwnerType": ".types",
    "GetUboRulesV1SendersResponse": ".types",
    "GetUboRulesV1SendersResponseData": ".types",
    "GetUboRulesV1SendersResponseDataOwner": ".types",
    "GetUboRulesV1SendersResponseDataOwnerType": ".types",
    "GetUboRulesV1SendersResponseDataRules": ".types",
    "GetUboRulesV1SendersResponseDataRulesUbo": ".types",
    "GetUboRulesV2SendersRequestOwnerType": ".types",
    "GetUboRulesV2SendersResponse": ".types",
    "GetUboRulesV2SendersResponseData": ".types",
    "GetUboRulesV2SendersResponseDataOwner": ".types",
    "GetUboRulesV2SendersResponseDataOwnerType": ".types",
    "GetUboRulesV2SendersResponseDataRules": ".types",
    "GetUboRulesV2SendersResponseDataRulesUbo": ".types",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItem": ".types",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem": ".types",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem": ".types",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory": ".types",
    "GetV1SendersRequestOwnerType": ".types",
    "GetV1SendersResponse": ".types",
    "GetV1SendersResponseData": ".types",
    "GetV1SendersResponseDataOwner": ".types",
    "GetV1SendersResponseDataOwnerType": ".types",
    "GetV1SendersResponseDataRules": ".types",
    "GetV1SendersResponseDataRulesRequiredDocumentsItem": ".types",
    "GetV1SendersResponseDataRulesRequiredDocumentsItemType": ".types",
    "GetV1SendersResponseDataRulesUbo": ".types",
    "GetV2SendersRequestOwnerType": ".types",
    "GetV2SendersResponse": ".types",
    "GetV2SendersResponseData": ".types",
    "GetV2SendersResponseDataOwner": ".types",
    "GetV2SendersResponseDataOwnerType": ".types",
    "GetV2SendersResponseDataRules": ".types",
    "GetV2SendersResponseDataRulesRequiredDocumentsItem": ".types",
    "GetV2SendersResponseDataRulesRequiredDocumentsItemType": ".types",
    "GetV2SendersResponseDataRulesRequiredFieldsItem": ".types",
    "GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItem": ".types",
    "GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem": ".types",
    "GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory": ".types",
    "GetV2SendersResponseDataRulesUbo": ".types",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItem": ".types",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem": ".types",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem": ".types",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory": ".types",
    "ListCountriesSendersResponse": ".types",
    "ListDocumentTypesV1SendersRequestOwnerType": ".types",
    "ListDocumentTypesV1SendersResponse": ".types",
    "ListDocumentTypesV1SendersResponseData": ".types",
    "ListDocumentTypesV1SendersResponseDataOwner": ".types",
    "ListDocumentTypesV1SendersResponseDataOwnerType": ".types",
    "ListDocumentTypesV1SendersResponseDataRules": ".types",
    "ListDocumentTypesV1SendersResponseDataRulesRequiredDocumentsItem": ".types",
    "ListDocumentTypesV1SendersResponseDataRulesRequiredDocumentsItemType": ".types",
    "ListDocumentTypesV2SendersRequestOwnerType": ".types",
    "ListDocumentTypesV2SendersResponse": ".types",
    "ListDocumentTypesV2SendersResponseData": ".types",
    "ListDocumentTypesV2SendersResponseDataOwner": ".types",
    "ListDocumentTypesV2SendersResponseDataOwnerType": ".types",
    "ListDocumentTypesV2SendersResponseDataRules": ".types",
    "ListDocumentTypesV2SendersResponseDataRulesRequiredDocumentsItem": ".types",
    "ListDocumentTypesV2SendersResponseDataRulesRequiredDocumentsItemType": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetUboRulesV1SendersRequestOwnerType",
    "GetUboRulesV1SendersResponse",
    "GetUboRulesV1SendersResponseData",
    "GetUboRulesV1SendersResponseDataOwner",
    "GetUboRulesV1SendersResponseDataOwnerType",
    "GetUboRulesV1SendersResponseDataRules",
    "GetUboRulesV1SendersResponseDataRulesUbo",
    "GetUboRulesV2SendersRequestOwnerType",
    "GetUboRulesV2SendersResponse",
    "GetUboRulesV2SendersResponseData",
    "GetUboRulesV2SendersResponseDataOwner",
    "GetUboRulesV2SendersResponseDataOwnerType",
    "GetUboRulesV2SendersResponseDataRules",
    "GetUboRulesV2SendersResponseDataRulesUbo",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItem",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem",
    "GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory",
    "GetV1SendersRequestOwnerType",
    "GetV1SendersResponse",
    "GetV1SendersResponseData",
    "GetV1SendersResponseDataOwner",
    "GetV1SendersResponseDataOwnerType",
    "GetV1SendersResponseDataRules",
    "GetV1SendersResponseDataRulesRequiredDocumentsItem",
    "GetV1SendersResponseDataRulesRequiredDocumentsItemType",
    "GetV1SendersResponseDataRulesUbo",
    "GetV2SendersRequestOwnerType",
    "GetV2SendersResponse",
    "GetV2SendersResponseData",
    "GetV2SendersResponseDataOwner",
    "GetV2SendersResponseDataOwnerType",
    "GetV2SendersResponseDataRules",
    "GetV2SendersResponseDataRulesRequiredDocumentsItem",
    "GetV2SendersResponseDataRulesRequiredDocumentsItemType",
    "GetV2SendersResponseDataRulesRequiredFieldsItem",
    "GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItem",
    "GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem",
    "GetV2SendersResponseDataRulesRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory",
    "GetV2SendersResponseDataRulesUbo",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItem",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItem",
    "GetV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItemSupportedDocumentTypesItemCategory",
    "ListCountriesSendersResponse",
    "ListDocumentTypesV1SendersRequestOwnerType",
    "ListDocumentTypesV1SendersResponse",
    "ListDocumentTypesV1SendersResponseData",
    "ListDocumentTypesV1SendersResponseDataOwner",
    "ListDocumentTypesV1SendersResponseDataOwnerType",
    "ListDocumentTypesV1SendersResponseDataRules",
    "ListDocumentTypesV1SendersResponseDataRulesRequiredDocumentsItem",
    "ListDocumentTypesV1SendersResponseDataRulesRequiredDocumentsItemType",
    "ListDocumentTypesV2SendersRequestOwnerType",
    "ListDocumentTypesV2SendersResponse",
    "ListDocumentTypesV2SendersResponseData",
    "ListDocumentTypesV2SendersResponseDataOwner",
    "ListDocumentTypesV2SendersResponseDataOwnerType",
    "ListDocumentTypesV2SendersResponseDataRules",
    "ListDocumentTypesV2SendersResponseDataRulesRequiredDocumentsItem",
    "ListDocumentTypesV2SendersResponseDataRulesRequiredDocumentsItemType",
]
