# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.address import Address
from .raw_client import AsyncRawUbosClient, RawUbosClient
from .types.create_ubos_request_address import CreateUbosRequestAddress
from .types.create_ubos_request_identity import CreateUbosRequestIdentity
from .types.create_ubos_request_pep_questionnaire import CreateUbosRequestPepQuestionnaire
from .types.create_ubos_response import CreateUbosResponse
from .types.delete_ubos_response import DeleteUbosResponse
from .types.get_ubos_response import GetUbosResponse
from .types.get_verification_url_ubos_request_action import GetVerificationUrlUbosRequestAction
from .types.get_verification_url_ubos_response import GetVerificationUrlUbosResponse
from .types.update_ubos_request_identity import UpdateUbosRequestIdentity
from .types.update_ubos_request_pep_questionnaire import UpdateUbosRequestPepQuestionnaire
from .types.update_ubos_response import UpdateUbosResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UbosClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUbosClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUbosClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUbosClient
        """
        return self._raw_client

    def create(
        self,
        *,
        first_name: str,
        last_name: str,
        birth_date: dt.date,
        phone: str,
        email: str,
        ownership_percent: float,
        address: CreateUbosRequestAddress,
        sender_id: str,
        identity: CreateUbosRequestIdentity,
        pep_declaration: bool,
        nationality: typing.Optional[str] = OMIT,
        identification_number: typing.Optional[str] = OMIT,
        verification_report: typing.Optional[str] = OMIT,
        verification_report_file_name: typing.Optional[str] = OMIT,
        sof_document: typing.Optional[str] = OMIT,
        pep_questionnaire: typing.Optional[CreateUbosRequestPepQuestionnaire] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateUbosResponse:
        """
        Creates a new UBO (Ultimate Beneficial Owner) for a specific sender. Note: Document requirements (documentFront, documentBack) vary by country. Please refer to the validation-rules endpoint with ownerType='business' and the specific country to determine exact documentation requirements. Multiple UBOs can be added by calling this endpoint multiple times. The total ownership percentage across all UBOs should not exceed 100%.

        Additional v2 details:
        * `pepDeclaration` is required.
        * `verificationReport` and `verificationReportFileName` are supported.
        * The total request payload size must be less than 10 MB.
        * `sofDocument` is required when any of the following is true:
          * UBO age is less than 25
          * UBO age is greater than 60
          * `pepDeclaration` is `true`
          * `address.country` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`
          * `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`
        * `pepQuestionnaire` is supported. It is required when `pepDeclaration` is `true`.
        * `pepQuestionnaire.declarationType` controls which section is required: `self` (for `SELF`) or `association` (for `IMMEDIATE_FAMILY` and `CLOSE_ASSOCIATE`).

        Parameters
        ----------
        first_name : str
            First name of the UBO.

        last_name : str
            Last name of the UBO.

        birth_date : dt.date
            Birthdate of the UBO in the format YYYY-MM-DD.

        phone : str
            Phone number of the UBO in international format (for example, +11234567890).

        email : str
            Email address of the UBO.

        ownership_percent : float
            Ownership percentage of the UBO in the company.

        address : CreateUbosRequestAddress
            UBO postal address.

        sender_id : str
            Unique identifier for the sender.

        identity : CreateUbosRequestIdentity
            Identity information for the UBO.

        pep_declaration : bool
            Whether the UBO is politically exposed. This field is required.

        nationality : typing.Optional[str]
            UBO nationality as an ISO 3166-1 alpha-2 country code. This is distinct from residence and identity-document country.

        identification_number : typing.Optional[str]
            Tax identification number for the UBO. Required for a non-US UBO when `usd_account` is requested.

        verification_report : typing.Optional[str]
            Optional base64 encoded verification report document.

        verification_report_file_name : typing.Optional[str]
            Optional file name for the verification report.

        sof_document : typing.Optional[str]
            Base64 encoded source-of-funds document. Required when the UBO is younger than 25 or older than 60, when `pepDeclaration` is `true`, or when either `address.country` or `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`.

        pep_questionnaire : typing.Optional[CreateUbosRequestPepQuestionnaire]
            Required when `pepDeclaration` is true. Contains declarationType with conditional `self` or `association` sections.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateUbosResponse
            Ultimate Beneficial Owner created successfully

        Examples
        --------
        import datetime

        from mesta import Mesta
        from mesta.senders.ubos import (
            CreateUbosRequestAddress,
            CreateUbosRequestIdentity,
        )

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.senders.ubos.create(
            first_name="firstName",
            last_name="lastName",
            birth_date=datetime.date.fromisoformat(
                "2023-01-15",
            ),
            phone="phone",
            email="email",
            ownership_percent=1.1,
            address=CreateUbosRequestAddress(
                street="street",
                city="city",
                postal_code="postalCode",
                country="country",
            ),
            sender_id="senderId",
            identity=CreateUbosRequestIdentity(
                document_type="PASSPORT",
                country_code="countryCode",
                document_number="documentNumber",
            ),
            pep_declaration=True,
        )
        """
        _response = self._raw_client.create(
            first_name=first_name,
            last_name=last_name,
            birth_date=birth_date,
            phone=phone,
            email=email,
            ownership_percent=ownership_percent,
            address=address,
            sender_id=sender_id,
            identity=identity,
            pep_declaration=pep_declaration,
            nationality=nationality,
            identification_number=identification_number,
            verification_report=verification_report,
            verification_report_file_name=verification_report_file_name,
            sof_document=sof_document,
            pep_questionnaire=pep_questionnaire,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetUbosResponse:
        """
        Retrieves details of a specific Ultimate Beneficial Owner (UBO)

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUbosResponse
            Ultimate Beneficial Owner details retrieved successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.senders.ubos.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteUbosResponse:
        """
        Deletes an existing UBO (Ultimate Beneficial Owner)

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteUbosResponse
            UBO deleted successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.senders.ubos.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        birth_date: typing.Optional[dt.date] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        nationality: typing.Optional[str] = OMIT,
        identification_number: typing.Optional[str] = OMIT,
        ownership_percent: typing.Optional[float] = OMIT,
        address: typing.Optional[Address] = OMIT,
        identity: typing.Optional[UpdateUbosRequestIdentity] = OMIT,
        verification_report: typing.Optional[str] = OMIT,
        verification_report_file_name: typing.Optional[str] = OMIT,
        pep_declaration: typing.Optional[bool] = OMIT,
        sof_document: typing.Optional[str] = OMIT,
        pep_questionnaire: typing.Optional[UpdateUbosRequestPepQuestionnaire] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateUbosResponse:
        """
        Updates an existing Ultimate Beneficial Owner (UBO). In addition to the base UBO fields, this endpoint supports `pepDeclaration`, `verificationReport`, and `sofDocument`. `sofDocument` is required when the UBO is younger than 25 or older than 60, when `pepDeclaration` is `true`, or when either `address.country` or `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`. `pepQuestionnaire` is supported. When `pepDeclaration` is `true`, include `pepQuestionnaire` with `declarationType` and the matching conditional section (`self` or `association`).

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        first_name : typing.Optional[str]
            First name of the UBO

        last_name : typing.Optional[str]
            Last name of the UBO

        birth_date : typing.Optional[dt.date]
            Birth date of the UBO

        email : typing.Optional[str]
            Email address of the UBO

        phone : typing.Optional[str]
            Phone number of the UBO in international format (e.g., +11234567890)

        nationality : typing.Optional[str]
            UBO nationality as an ISO 3166-1 alpha-2 country code. This is distinct from residence and identity-document country.

        identification_number : typing.Optional[str]
            Tax identification number for the UBO. Required for a non-US UBO when `usd_account` is requested.

        ownership_percent : typing.Optional[float]
            Percentage of the sender owned by this UBO.

        address : typing.Optional[Address]

        identity : typing.Optional[UpdateUbosRequestIdentity]

        verification_report : typing.Optional[str]
            Optional base64 encoded verification report document.

        verification_report_file_name : typing.Optional[str]
            Optional file name for the verification report.

        pep_declaration : typing.Optional[bool]
            Whether the UBO is politically exposed.

        sof_document : typing.Optional[str]
            Base64 encoded source-of-funds document. Required when the UBO is younger than 25 or older than 60, when `pepDeclaration` is `true`, or when either `address.country` or `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`.

        pep_questionnaire : typing.Optional[UpdateUbosRequestPepQuestionnaire]
            Required when `pepDeclaration` is true. Contains declarationType with conditional `self` or `association` sections.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateUbosResponse
            Ultimate Beneficial Owner updated successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.senders.ubos.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            first_name=first_name,
            last_name=last_name,
            birth_date=birth_date,
            email=email,
            phone=phone,
            nationality=nationality,
            identification_number=identification_number,
            ownership_percent=ownership_percent,
            address=address,
            identity=identity,
            verification_report=verification_report,
            verification_report_file_name=verification_report_file_name,
            pep_declaration=pep_declaration,
            sof_document=sof_document,
            pep_questionnaire=pep_questionnaire,
            request_options=request_options,
        )
        return _response.data

    def get_verification_url(
        self,
        id: str,
        *,
        action: typing.Optional[GetVerificationUrlUbosRequestAction] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetVerificationUrlUbosResponse:
        """
        Fetches the latest selfie verification session for a UBO and, optionally, generates or regenerates a verification link.

        Action behavior:
        * no `action`: return the current verification-session state without creating a new link.
        * `GENERATE`: create the first verification link only when no previous selfie session exists.
        * `REGENERATE`: create a fresh verification link only when the latest session is `DECLINED` or `EXPIRED`.

        Response behavior:
        * `latestSession`: the most recent selfie verification session, or `null` if none exists.
        * `previousSessions`: older selfie verification sessions in reverse chronological order.

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        action : typing.Optional[GetVerificationUrlUbosRequestAction]
            Optional action for selfie-link creation. Omit it to fetch the current session state only. Use `GENERATE` to create the first link when no session exists. Use `REGENERATE` only when the latest session is `DECLINED` or `EXPIRED`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetVerificationUrlUbosResponse
            UBO verification session fetched successfully

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.senders.ubos.get_verification_url(
            id="id",
        )
        """
        _response = self._raw_client.get_verification_url(id, action=action, request_options=request_options)
        return _response.data


class AsyncUbosClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUbosClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUbosClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUbosClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        first_name: str,
        last_name: str,
        birth_date: dt.date,
        phone: str,
        email: str,
        ownership_percent: float,
        address: CreateUbosRequestAddress,
        sender_id: str,
        identity: CreateUbosRequestIdentity,
        pep_declaration: bool,
        nationality: typing.Optional[str] = OMIT,
        identification_number: typing.Optional[str] = OMIT,
        verification_report: typing.Optional[str] = OMIT,
        verification_report_file_name: typing.Optional[str] = OMIT,
        sof_document: typing.Optional[str] = OMIT,
        pep_questionnaire: typing.Optional[CreateUbosRequestPepQuestionnaire] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateUbosResponse:
        """
        Creates a new UBO (Ultimate Beneficial Owner) for a specific sender. Note: Document requirements (documentFront, documentBack) vary by country. Please refer to the validation-rules endpoint with ownerType='business' and the specific country to determine exact documentation requirements. Multiple UBOs can be added by calling this endpoint multiple times. The total ownership percentage across all UBOs should not exceed 100%.

        Additional v2 details:
        * `pepDeclaration` is required.
        * `verificationReport` and `verificationReportFileName` are supported.
        * The total request payload size must be less than 10 MB.
        * `sofDocument` is required when any of the following is true:
          * UBO age is less than 25
          * UBO age is greater than 60
          * `pepDeclaration` is `true`
          * `address.country` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`
          * `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`
        * `pepQuestionnaire` is supported. It is required when `pepDeclaration` is `true`.
        * `pepQuestionnaire.declarationType` controls which section is required: `self` (for `SELF`) or `association` (for `IMMEDIATE_FAMILY` and `CLOSE_ASSOCIATE`).

        Parameters
        ----------
        first_name : str
            First name of the UBO.

        last_name : str
            Last name of the UBO.

        birth_date : dt.date
            Birthdate of the UBO in the format YYYY-MM-DD.

        phone : str
            Phone number of the UBO in international format (for example, +11234567890).

        email : str
            Email address of the UBO.

        ownership_percent : float
            Ownership percentage of the UBO in the company.

        address : CreateUbosRequestAddress
            UBO postal address.

        sender_id : str
            Unique identifier for the sender.

        identity : CreateUbosRequestIdentity
            Identity information for the UBO.

        pep_declaration : bool
            Whether the UBO is politically exposed. This field is required.

        nationality : typing.Optional[str]
            UBO nationality as an ISO 3166-1 alpha-2 country code. This is distinct from residence and identity-document country.

        identification_number : typing.Optional[str]
            Tax identification number for the UBO. Required for a non-US UBO when `usd_account` is requested.

        verification_report : typing.Optional[str]
            Optional base64 encoded verification report document.

        verification_report_file_name : typing.Optional[str]
            Optional file name for the verification report.

        sof_document : typing.Optional[str]
            Base64 encoded source-of-funds document. Required when the UBO is younger than 25 or older than 60, when `pepDeclaration` is `true`, or when either `address.country` or `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`.

        pep_questionnaire : typing.Optional[CreateUbosRequestPepQuestionnaire]
            Required when `pepDeclaration` is true. Contains declarationType with conditional `self` or `association` sections.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateUbosResponse
            Ultimate Beneficial Owner created successfully

        Examples
        --------
        import asyncio
        import datetime

        from mesta import AsyncMesta
        from mesta.senders.ubos import (
            CreateUbosRequestAddress,
            CreateUbosRequestIdentity,
        )

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.senders.ubos.create(
                first_name="firstName",
                last_name="lastName",
                birth_date=datetime.date.fromisoformat(
                    "2023-01-15",
                ),
                phone="phone",
                email="email",
                ownership_percent=1.1,
                address=CreateUbosRequestAddress(
                    street="street",
                    city="city",
                    postal_code="postalCode",
                    country="country",
                ),
                sender_id="senderId",
                identity=CreateUbosRequestIdentity(
                    document_type="PASSPORT",
                    country_code="countryCode",
                    document_number="documentNumber",
                ),
                pep_declaration=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            first_name=first_name,
            last_name=last_name,
            birth_date=birth_date,
            phone=phone,
            email=email,
            ownership_percent=ownership_percent,
            address=address,
            sender_id=sender_id,
            identity=identity,
            pep_declaration=pep_declaration,
            nationality=nationality,
            identification_number=identification_number,
            verification_report=verification_report,
            verification_report_file_name=verification_report_file_name,
            sof_document=sof_document,
            pep_questionnaire=pep_questionnaire,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetUbosResponse:
        """
        Retrieves details of a specific Ultimate Beneficial Owner (UBO)

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUbosResponse
            Ultimate Beneficial Owner details retrieved successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.senders.ubos.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteUbosResponse:
        """
        Deletes an existing UBO (Ultimate Beneficial Owner)

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteUbosResponse
            UBO deleted successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.senders.ubos.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        birth_date: typing.Optional[dt.date] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        nationality: typing.Optional[str] = OMIT,
        identification_number: typing.Optional[str] = OMIT,
        ownership_percent: typing.Optional[float] = OMIT,
        address: typing.Optional[Address] = OMIT,
        identity: typing.Optional[UpdateUbosRequestIdentity] = OMIT,
        verification_report: typing.Optional[str] = OMIT,
        verification_report_file_name: typing.Optional[str] = OMIT,
        pep_declaration: typing.Optional[bool] = OMIT,
        sof_document: typing.Optional[str] = OMIT,
        pep_questionnaire: typing.Optional[UpdateUbosRequestPepQuestionnaire] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateUbosResponse:
        """
        Updates an existing Ultimate Beneficial Owner (UBO). In addition to the base UBO fields, this endpoint supports `pepDeclaration`, `verificationReport`, and `sofDocument`. `sofDocument` is required when the UBO is younger than 25 or older than 60, when `pepDeclaration` is `true`, or when either `address.country` or `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`. `pepQuestionnaire` is supported. When `pepDeclaration` is `true`, include `pepQuestionnaire` with `declarationType` and the matching conditional section (`self` or `association`).

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        first_name : typing.Optional[str]
            First name of the UBO

        last_name : typing.Optional[str]
            Last name of the UBO

        birth_date : typing.Optional[dt.date]
            Birth date of the UBO

        email : typing.Optional[str]
            Email address of the UBO

        phone : typing.Optional[str]
            Phone number of the UBO in international format (e.g., +11234567890)

        nationality : typing.Optional[str]
            UBO nationality as an ISO 3166-1 alpha-2 country code. This is distinct from residence and identity-document country.

        identification_number : typing.Optional[str]
            Tax identification number for the UBO. Required for a non-US UBO when `usd_account` is requested.

        ownership_percent : typing.Optional[float]
            Percentage of the sender owned by this UBO.

        address : typing.Optional[Address]

        identity : typing.Optional[UpdateUbosRequestIdentity]

        verification_report : typing.Optional[str]
            Optional base64 encoded verification report document.

        verification_report_file_name : typing.Optional[str]
            Optional file name for the verification report.

        pep_declaration : typing.Optional[bool]
            Whether the UBO is politically exposed.

        sof_document : typing.Optional[str]
            Base64 encoded source-of-funds document. Required when the UBO is younger than 25 or older than 60, when `pepDeclaration` is `true`, or when either `address.country` or `identity.countryCode` is one of: `DZ`, `AO`, `BO`, `BG`, `BF`, `CM`, `CI`, `ET`, `HT`, `IQ`, `KE`, `LA`, `LB`, `ML`, `MC`, `MZ`, `NA`, `NP`, `NI`, `NG`, `SO`, `SY`, `VN`, `VG`, `YE`.

        pep_questionnaire : typing.Optional[UpdateUbosRequestPepQuestionnaire]
            Required when `pepDeclaration` is true. Contains declarationType with conditional `self` or `association` sections.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateUbosResponse
            Ultimate Beneficial Owner updated successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.senders.ubos.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            first_name=first_name,
            last_name=last_name,
            birth_date=birth_date,
            email=email,
            phone=phone,
            nationality=nationality,
            identification_number=identification_number,
            ownership_percent=ownership_percent,
            address=address,
            identity=identity,
            verification_report=verification_report,
            verification_report_file_name=verification_report_file_name,
            pep_declaration=pep_declaration,
            sof_document=sof_document,
            pep_questionnaire=pep_questionnaire,
            request_options=request_options,
        )
        return _response.data

    async def get_verification_url(
        self,
        id: str,
        *,
        action: typing.Optional[GetVerificationUrlUbosRequestAction] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetVerificationUrlUbosResponse:
        """
        Fetches the latest selfie verification session for a UBO and, optionally, generates or regenerates a verification link.

        Action behavior:
        * no `action`: return the current verification-session state without creating a new link.
        * `GENERATE`: create the first verification link only when no previous selfie session exists.
        * `REGENERATE`: create a fresh verification link only when the latest session is `DECLINED` or `EXPIRED`.

        Response behavior:
        * `latestSession`: the most recent selfie verification session, or `null` if none exists.
        * `previousSessions`: older selfie verification sessions in reverse chronological order.

        Parameters
        ----------
        id : str
            Unique identifier of the UBO

        action : typing.Optional[GetVerificationUrlUbosRequestAction]
            Optional action for selfie-link creation. Omit it to fetch the current session state only. Use `GENERATE` to create the first link when no session exists. Use `REGENERATE` only when the latest session is `DECLINED` or `EXPIRED`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetVerificationUrlUbosResponse
            UBO verification session fetched successfully

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.senders.ubos.get_verification_url(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_verification_url(id, action=action, request_options=request_options)
        return _response.data
