# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_senders_request import CreateSendersRequest
    from .create_senders_response import CreateSendersResponse
    from .create_senders_response_data import CreateSendersResponseData
    from .create_senders_response_data_addresses_item import CreateSendersResponseDataAddressesItem
    from .create_senders_response_data_business_type import CreateSendersResponseDataBusinessType
    from .create_senders_response_data_documents_item import CreateSendersResponseDataDocumentsItem
    from .create_senders_response_data_documents_item_type import CreateSendersResponseDataDocumentsItemType
    from .create_senders_response_data_gender import CreateSendersResponseDataGender
    from .create_senders_response_data_identity import CreateSendersResponseDataIdentity
    from .create_senders_response_data_identity_document_type import CreateSendersResponseDataIdentityDocumentType
    from .create_senders_response_data_kyb import CreateSendersResponseDataKyb
    from .create_senders_response_data_kyb_status import CreateSendersResponseDataKybStatus
    from .create_senders_response_data_risk_score import CreateSendersResponseDataRiskScore
    from .create_senders_response_data_status import CreateSendersResponseDataStatus
    from .create_senders_response_data_tos import CreateSendersResponseDataTos
    from .create_senders_response_data_tos_link import CreateSendersResponseDataTosLink
    from .create_senders_response_data_tos_status import CreateSendersResponseDataTosStatus
    from .create_senders_response_data_type import CreateSendersResponseDataType
    from .delete_senders_response import DeleteSendersResponse
    from .get_balances_senders_response import GetBalancesSendersResponse
    from .get_balances_senders_response_data_item import GetBalancesSendersResponseDataItem
    from .get_senders_response import GetSendersResponse
    from .get_senders_response_data import GetSendersResponseData
    from .get_senders_response_data_addresses_item import GetSendersResponseDataAddressesItem
    from .get_senders_response_data_business_type import GetSendersResponseDataBusinessType
    from .get_senders_response_data_deposit_bank_accounts_item import GetSendersResponseDataDepositBankAccountsItem
    from .get_senders_response_data_deposit_bank_accounts_item_bank_details import (
        GetSendersResponseDataDepositBankAccountsItemBankDetails,
    )
    from .get_senders_response_data_deposit_bank_accounts_item_routing_details_item import (
        GetSendersResponseDataDepositBankAccountsItemRoutingDetailsItem,
    )
    from .get_senders_response_data_deposit_wallet_addresses_item import (
        GetSendersResponseDataDepositWalletAddressesItem,
    )
    from .get_senders_response_data_documents_item import GetSendersResponseDataDocumentsItem
    from .get_senders_response_data_documents_item_type import GetSendersResponseDataDocumentsItemType
    from .get_senders_response_data_gender import GetSendersResponseDataGender
    from .get_senders_response_data_identity import GetSendersResponseDataIdentity
    from .get_senders_response_data_identity_document_back import GetSendersResponseDataIdentityDocumentBack
    from .get_senders_response_data_identity_document_front import GetSendersResponseDataIdentityDocumentFront
    from .get_senders_response_data_identity_document_type import GetSendersResponseDataIdentityDocumentType
    from .get_senders_response_data_kyb import GetSendersResponseDataKyb
    from .get_senders_response_data_kyb_status import GetSendersResponseDataKybStatus
    from .get_senders_response_data_kyc import GetSendersResponseDataKyc
    from .get_senders_response_data_kyc_status import GetSendersResponseDataKycStatus
    from .get_senders_response_data_status import GetSendersResponseDataStatus
    from .get_senders_response_data_tos import GetSendersResponseDataTos
    from .get_senders_response_data_tos_link import GetSendersResponseDataTosLink
    from .get_senders_response_data_tos_status import GetSendersResponseDataTosStatus
    from .get_senders_response_data_type import GetSendersResponseDataType
    from .get_senders_response_data_ubo_item import GetSendersResponseDataUboItem
    from .get_senders_response_data_ubo_item_address import GetSendersResponseDataUboItemAddress
    from .get_senders_response_data_ubo_item_documents_item import GetSendersResponseDataUboItemDocumentsItem
    from .get_senders_response_data_ubo_item_documents_item_type import GetSendersResponseDataUboItemDocumentsItemType
    from .get_senders_response_data_ubo_item_identity import GetSendersResponseDataUboItemIdentity
    from .get_senders_response_data_ubo_item_identity_document_back import (
        GetSendersResponseDataUboItemIdentityDocumentBack,
    )
    from .get_senders_response_data_ubo_item_identity_document_front import (
        GetSendersResponseDataUboItemIdentityDocumentFront,
    )
    from .get_senders_response_data_ubo_item_identity_document_type import (
        GetSendersResponseDataUboItemIdentityDocumentType,
    )
    from .get_senders_response_data_ubo_item_kyc import GetSendersResponseDataUboItemKyc
    from .get_senders_response_data_ubo_item_kyc_status import GetSendersResponseDataUboItemKycStatus
    from .get_senders_response_data_ubo_item_pep_questionnaire import GetSendersResponseDataUboItemPepQuestionnaire
    from .get_senders_response_data_ubo_item_pep_questionnaire_association import (
        GetSendersResponseDataUboItemPepQuestionnaireAssociation,
    )
    from .get_senders_response_data_ubo_item_pep_questionnaire_declaration_type import (
        GetSendersResponseDataUboItemPepQuestionnaireDeclarationType,
    )
    from .get_senders_response_data_ubo_item_pep_questionnaire_self import (
        GetSendersResponseDataUboItemPepQuestionnaireSelf,
    )
    from .get_senders_response_data_ubo_item_pep_questionnaire_self_pep_category import (
        GetSendersResponseDataUboItemPepQuestionnaireSelfPepCategory,
    )
    from .list_senders_request_sort_by import ListSendersRequestSortBy
    from .list_senders_request_sort_order import ListSendersRequestSortOrder
    from .list_senders_request_status import ListSendersRequestStatus
    from .list_senders_response import ListSendersResponse
    from .list_senders_response_data_item import ListSendersResponseDataItem
    from .list_senders_response_data_item_addresses_item import ListSendersResponseDataItemAddressesItem
    from .list_senders_response_data_item_business_type import ListSendersResponseDataItemBusinessType
    from .list_senders_response_data_item_documents_item import ListSendersResponseDataItemDocumentsItem
    from .list_senders_response_data_item_documents_item_type import ListSendersResponseDataItemDocumentsItemType
    from .list_senders_response_data_item_gender import ListSendersResponseDataItemGender
    from .list_senders_response_data_item_identity import ListSendersResponseDataItemIdentity
    from .list_senders_response_data_item_identity_document_type import ListSendersResponseDataItemIdentityDocumentType
    from .list_senders_response_data_item_kyb import ListSendersResponseDataItemKyb
    from .list_senders_response_data_item_kyb_status import ListSendersResponseDataItemKybStatus
    from .list_senders_response_data_item_kyc import ListSendersResponseDataItemKyc
    from .list_senders_response_data_item_kyc_status import ListSendersResponseDataItemKycStatus
    from .list_senders_response_data_item_status import ListSendersResponseDataItemStatus
    from .list_senders_response_data_item_tos import ListSendersResponseDataItemTos
    from .list_senders_response_data_item_tos_link import ListSendersResponseDataItemTosLink
    from .list_senders_response_data_item_tos_status import ListSendersResponseDataItemTosStatus
    from .list_senders_response_data_item_type import ListSendersResponseDataItemType
    from .simulate_deposit_senders_response import SimulateDepositSendersResponse
    from .simulate_verification_result_senders_request_result import SimulateVerificationResultSendersRequestResult
    from .simulate_verification_result_senders_response import SimulateVerificationResultSendersResponse
    from .update_senders_request_body import UpdateSendersRequestBody
    from .update_senders_response import UpdateSendersResponse
    from .update_senders_response_data import UpdateSendersResponseData
    from .update_senders_response_data_addresses_item import UpdateSendersResponseDataAddressesItem
    from .update_senders_response_data_business_type import UpdateSendersResponseDataBusinessType
    from .update_senders_response_data_documents_item import UpdateSendersResponseDataDocumentsItem
    from .update_senders_response_data_documents_item_type import UpdateSendersResponseDataDocumentsItemType
    from .update_senders_response_data_gender import UpdateSendersResponseDataGender
    from .update_senders_response_data_identity import UpdateSendersResponseDataIdentity
    from .update_senders_response_data_identity_document_type import UpdateSendersResponseDataIdentityDocumentType
    from .update_senders_response_data_kyb import UpdateSendersResponseDataKyb
    from .update_senders_response_data_kyb_status import UpdateSendersResponseDataKybStatus
    from .update_senders_response_data_risk_score import UpdateSendersResponseDataRiskScore
    from .update_senders_response_data_status import UpdateSendersResponseDataStatus
    from .update_senders_response_data_tos import UpdateSendersResponseDataTos
    from .update_senders_response_data_tos_link import UpdateSendersResponseDataTosLink
    from .update_senders_response_data_tos_status import UpdateSendersResponseDataTosStatus
    from .update_senders_response_data_type import UpdateSendersResponseDataType
    from .verify_senders_response import VerifySendersResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateSendersRequest": ".create_senders_request",
    "CreateSendersResponse": ".create_senders_response",
    "CreateSendersResponseData": ".create_senders_response_data",
    "CreateSendersResponseDataAddressesItem": ".create_senders_response_data_addresses_item",
    "CreateSendersResponseDataBusinessType": ".create_senders_response_data_business_type",
    "CreateSendersResponseDataDocumentsItem": ".create_senders_response_data_documents_item",
    "CreateSendersResponseDataDocumentsItemType": ".create_senders_response_data_documents_item_type",
    "CreateSendersResponseDataGender": ".create_senders_response_data_gender",
    "CreateSendersResponseDataIdentity": ".create_senders_response_data_identity",
    "CreateSendersResponseDataIdentityDocumentType": ".create_senders_response_data_identity_document_type",
    "CreateSendersResponseDataKyb": ".create_senders_response_data_kyb",
    "CreateSendersResponseDataKybStatus": ".create_senders_response_data_kyb_status",
    "CreateSendersResponseDataRiskScore": ".create_senders_response_data_risk_score",
    "CreateSendersResponseDataStatus": ".create_senders_response_data_status",
    "CreateSendersResponseDataTos": ".create_senders_response_data_tos",
    "CreateSendersResponseDataTosLink": ".create_senders_response_data_tos_link",
    "CreateSendersResponseDataTosStatus": ".create_senders_response_data_tos_status",
    "CreateSendersResponseDataType": ".create_senders_response_data_type",
    "DeleteSendersResponse": ".delete_senders_response",
    "GetBalancesSendersResponse": ".get_balances_senders_response",
    "GetBalancesSendersResponseDataItem": ".get_balances_senders_response_data_item",
    "GetSendersResponse": ".get_senders_response",
    "GetSendersResponseData": ".get_senders_response_data",
    "GetSendersResponseDataAddressesItem": ".get_senders_response_data_addresses_item",
    "GetSendersResponseDataBusinessType": ".get_senders_response_data_business_type",
    "GetSendersResponseDataDepositBankAccountsItem": ".get_senders_response_data_deposit_bank_accounts_item",
    "GetSendersResponseDataDepositBankAccountsItemBankDetails": ".get_senders_response_data_deposit_bank_accounts_item_bank_details",
    "GetSendersResponseDataDepositBankAccountsItemRoutingDetailsItem": ".get_senders_response_data_deposit_bank_accounts_item_routing_details_item",
    "GetSendersResponseDataDepositWalletAddressesItem": ".get_senders_response_data_deposit_wallet_addresses_item",
    "GetSendersResponseDataDocumentsItem": ".get_senders_response_data_documents_item",
    "GetSendersResponseDataDocumentsItemType": ".get_senders_response_data_documents_item_type",
    "GetSendersResponseDataGender": ".get_senders_response_data_gender",
    "GetSendersResponseDataIdentity": ".get_senders_response_data_identity",
    "GetSendersResponseDataIdentityDocumentBack": ".get_senders_response_data_identity_document_back",
    "GetSendersResponseDataIdentityDocumentFront": ".get_senders_response_data_identity_document_front",
    "GetSendersResponseDataIdentityDocumentType": ".get_senders_response_data_identity_document_type",
    "GetSendersResponseDataKyb": ".get_senders_response_data_kyb",
    "GetSendersResponseDataKybStatus": ".get_senders_response_data_kyb_status",
    "GetSendersResponseDataKyc": ".get_senders_response_data_kyc",
    "GetSendersResponseDataKycStatus": ".get_senders_response_data_kyc_status",
    "GetSendersResponseDataStatus": ".get_senders_response_data_status",
    "GetSendersResponseDataTos": ".get_senders_response_data_tos",
    "GetSendersResponseDataTosLink": ".get_senders_response_data_tos_link",
    "GetSendersResponseDataTosStatus": ".get_senders_response_data_tos_status",
    "GetSendersResponseDataType": ".get_senders_response_data_type",
    "GetSendersResponseDataUboItem": ".get_senders_response_data_ubo_item",
    "GetSendersResponseDataUboItemAddress": ".get_senders_response_data_ubo_item_address",
    "GetSendersResponseDataUboItemDocumentsItem": ".get_senders_response_data_ubo_item_documents_item",
    "GetSendersResponseDataUboItemDocumentsItemType": ".get_senders_response_data_ubo_item_documents_item_type",
    "GetSendersResponseDataUboItemIdentity": ".get_senders_response_data_ubo_item_identity",
    "GetSendersResponseDataUboItemIdentityDocumentBack": ".get_senders_response_data_ubo_item_identity_document_back",
    "GetSendersResponseDataUboItemIdentityDocumentFront": ".get_senders_response_data_ubo_item_identity_document_front",
    "GetSendersResponseDataUboItemIdentityDocumentType": ".get_senders_response_data_ubo_item_identity_document_type",
    "GetSendersResponseDataUboItemKyc": ".get_senders_response_data_ubo_item_kyc",
    "GetSendersResponseDataUboItemKycStatus": ".get_senders_response_data_ubo_item_kyc_status",
    "GetSendersResponseDataUboItemPepQuestionnaire": ".get_senders_response_data_ubo_item_pep_questionnaire",
    "GetSendersResponseDataUboItemPepQuestionnaireAssociation": ".get_senders_response_data_ubo_item_pep_questionnaire_association",
    "GetSendersResponseDataUboItemPepQuestionnaireDeclarationType": ".get_senders_response_data_ubo_item_pep_questionnaire_declaration_type",
    "GetSendersResponseDataUboItemPepQuestionnaireSelf": ".get_senders_response_data_ubo_item_pep_questionnaire_self",
    "GetSendersResponseDataUboItemPepQuestionnaireSelfPepCategory": ".get_senders_response_data_ubo_item_pep_questionnaire_self_pep_category",
    "ListSendersRequestSortBy": ".list_senders_request_sort_by",
    "ListSendersRequestSortOrder": ".list_senders_request_sort_order",
    "ListSendersRequestStatus": ".list_senders_request_status",
    "ListSendersResponse": ".list_senders_response",
    "ListSendersResponseDataItem": ".list_senders_response_data_item",
    "ListSendersResponseDataItemAddressesItem": ".list_senders_response_data_item_addresses_item",
    "ListSendersResponseDataItemBusinessType": ".list_senders_response_data_item_business_type",
    "ListSendersResponseDataItemDocumentsItem": ".list_senders_response_data_item_documents_item",
    "ListSendersResponseDataItemDocumentsItemType": ".list_senders_response_data_item_documents_item_type",
    "ListSendersResponseDataItemGender": ".list_senders_response_data_item_gender",
    "ListSendersResponseDataItemIdentity": ".list_senders_response_data_item_identity",
    "ListSendersResponseDataItemIdentityDocumentType": ".list_senders_response_data_item_identity_document_type",
    "ListSendersResponseDataItemKyb": ".list_senders_response_data_item_kyb",
    "ListSendersResponseDataItemKybStatus": ".list_senders_response_data_item_kyb_status",
    "ListSendersResponseDataItemKyc": ".list_senders_response_data_item_kyc",
    "ListSendersResponseDataItemKycStatus": ".list_senders_response_data_item_kyc_status",
    "ListSendersResponseDataItemStatus": ".list_senders_response_data_item_status",
    "ListSendersResponseDataItemTos": ".list_senders_response_data_item_tos",
    "ListSendersResponseDataItemTosLink": ".list_senders_response_data_item_tos_link",
    "ListSendersResponseDataItemTosStatus": ".list_senders_response_data_item_tos_status",
    "ListSendersResponseDataItemType": ".list_senders_response_data_item_type",
    "SimulateDepositSendersResponse": ".simulate_deposit_senders_response",
    "SimulateVerificationResultSendersRequestResult": ".simulate_verification_result_senders_request_result",
    "SimulateVerificationResultSendersResponse": ".simulate_verification_result_senders_response",
    "UpdateSendersRequestBody": ".update_senders_request_body",
    "UpdateSendersResponse": ".update_senders_response",
    "UpdateSendersResponseData": ".update_senders_response_data",
    "UpdateSendersResponseDataAddressesItem": ".update_senders_response_data_addresses_item",
    "UpdateSendersResponseDataBusinessType": ".update_senders_response_data_business_type",
    "UpdateSendersResponseDataDocumentsItem": ".update_senders_response_data_documents_item",
    "UpdateSendersResponseDataDocumentsItemType": ".update_senders_response_data_documents_item_type",
    "UpdateSendersResponseDataGender": ".update_senders_response_data_gender",
    "UpdateSendersResponseDataIdentity": ".update_senders_response_data_identity",
    "UpdateSendersResponseDataIdentityDocumentType": ".update_senders_response_data_identity_document_type",
    "UpdateSendersResponseDataKyb": ".update_senders_response_data_kyb",
    "UpdateSendersResponseDataKybStatus": ".update_senders_response_data_kyb_status",
    "UpdateSendersResponseDataRiskScore": ".update_senders_response_data_risk_score",
    "UpdateSendersResponseDataStatus": ".update_senders_response_data_status",
    "UpdateSendersResponseDataTos": ".update_senders_response_data_tos",
    "UpdateSendersResponseDataTosLink": ".update_senders_response_data_tos_link",
    "UpdateSendersResponseDataTosStatus": ".update_senders_response_data_tos_status",
    "UpdateSendersResponseDataType": ".update_senders_response_data_type",
    "VerifySendersResponse": ".verify_senders_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateSendersRequest",
    "CreateSendersResponse",
    "CreateSendersResponseData",
    "CreateSendersResponseDataAddressesItem",
    "CreateSendersResponseDataBusinessType",
    "CreateSendersResponseDataDocumentsItem",
    "CreateSendersResponseDataDocumentsItemType",
    "CreateSendersResponseDataGender",
    "CreateSendersResponseDataIdentity",
    "CreateSendersResponseDataIdentityDocumentType",
    "CreateSendersResponseDataKyb",
    "CreateSendersResponseDataKybStatus",
    "CreateSendersResponseDataRiskScore",
    "CreateSendersResponseDataStatus",
    "CreateSendersResponseDataTos",
    "CreateSendersResponseDataTosLink",
    "CreateSendersResponseDataTosStatus",
    "CreateSendersResponseDataType",
    "DeleteSendersResponse",
    "GetBalancesSendersResponse",
    "GetBalancesSendersResponseDataItem",
    "GetSendersResponse",
    "GetSendersResponseData",
    "GetSendersResponseDataAddressesItem",
    "GetSendersResponseDataBusinessType",
    "GetSendersResponseDataDepositBankAccountsItem",
    "GetSendersResponseDataDepositBankAccountsItemBankDetails",
    "GetSendersResponseDataDepositBankAccountsItemRoutingDetailsItem",
    "GetSendersResponseDataDepositWalletAddressesItem",
    "GetSendersResponseDataDocumentsItem",
    "GetSendersResponseDataDocumentsItemType",
    "GetSendersResponseDataGender",
    "GetSendersResponseDataIdentity",
    "GetSendersResponseDataIdentityDocumentBack",
    "GetSendersResponseDataIdentityDocumentFront",
    "GetSendersResponseDataIdentityDocumentType",
    "GetSendersResponseDataKyb",
    "GetSendersResponseDataKybStatus",
    "GetSendersResponseDataKyc",
    "GetSendersResponseDataKycStatus",
    "GetSendersResponseDataStatus",
    "GetSendersResponseDataTos",
    "GetSendersResponseDataTosLink",
    "GetSendersResponseDataTosStatus",
    "GetSendersResponseDataType",
    "GetSendersResponseDataUboItem",
    "GetSendersResponseDataUboItemAddress",
    "GetSendersResponseDataUboItemDocumentsItem",
    "GetSendersResponseDataUboItemDocumentsItemType",
    "GetSendersResponseDataUboItemIdentity",
    "GetSendersResponseDataUboItemIdentityDocumentBack",
    "GetSendersResponseDataUboItemIdentityDocumentFront",
    "GetSendersResponseDataUboItemIdentityDocumentType",
    "GetSendersResponseDataUboItemKyc",
    "GetSendersResponseDataUboItemKycStatus",
    "GetSendersResponseDataUboItemPepQuestionnaire",
    "GetSendersResponseDataUboItemPepQuestionnaireAssociation",
    "GetSendersResponseDataUboItemPepQuestionnaireDeclarationType",
    "GetSendersResponseDataUboItemPepQuestionnaireSelf",
    "GetSendersResponseDataUboItemPepQuestionnaireSelfPepCategory",
    "ListSendersRequestSortBy",
    "ListSendersRequestSortOrder",
    "ListSendersRequestStatus",
    "ListSendersResponse",
    "ListSendersResponseDataItem",
    "ListSendersResponseDataItemAddressesItem",
    "ListSendersResponseDataItemBusinessType",
    "ListSendersResponseDataItemDocumentsItem",
    "ListSendersResponseDataItemDocumentsItemType",
    "ListSendersResponseDataItemGender",
    "ListSendersResponseDataItemIdentity",
    "ListSendersResponseDataItemIdentityDocumentType",
    "ListSendersResponseDataItemKyb",
    "ListSendersResponseDataItemKybStatus",
    "ListSendersResponseDataItemKyc",
    "ListSendersResponseDataItemKycStatus",
    "ListSendersResponseDataItemStatus",
    "ListSendersResponseDataItemTos",
    "ListSendersResponseDataItemTosLink",
    "ListSendersResponseDataItemTosStatus",
    "ListSendersResponseDataItemType",
    "SimulateDepositSendersResponse",
    "SimulateVerificationResultSendersRequestResult",
    "SimulateVerificationResultSendersResponse",
    "UpdateSendersRequestBody",
    "UpdateSendersResponse",
    "UpdateSendersResponseData",
    "UpdateSendersResponseDataAddressesItem",
    "UpdateSendersResponseDataBusinessType",
    "UpdateSendersResponseDataDocumentsItem",
    "UpdateSendersResponseDataDocumentsItemType",
    "UpdateSendersResponseDataGender",
    "UpdateSendersResponseDataIdentity",
    "UpdateSendersResponseDataIdentityDocumentType",
    "UpdateSendersResponseDataKyb",
    "UpdateSendersResponseDataKybStatus",
    "UpdateSendersResponseDataRiskScore",
    "UpdateSendersResponseDataStatus",
    "UpdateSendersResponseDataTos",
    "UpdateSendersResponseDataTosLink",
    "UpdateSendersResponseDataTosStatus",
    "UpdateSendersResponseDataType",
    "VerifySendersResponse",
]
