# This file was auto-generated by Fern from our API Definition.

import typing

GetSendersResponseDataUboItemKycStatus = typing.Union[
    typing.Literal["unverified", "pending", "approved", "declined"], typing.Any
]
