# This file was auto-generated by Fern from our API Definition.

import typing

GetSendersResponseDataUboItemPepQuestionnaireDeclarationType = typing.Union[
    typing.Literal["SELF", "IMMEDIATE_FAMILY", "CLOSE_ASSOCIATE"], typing.Any
]
