# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetSendersResponseDataDepositBankAccountsItemRoutingDetailsItem(UniversalBaseModel):
    routing_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="routingNumber"),
        pydantic.Field(alias="routingNumber", description="Routing number"),
    ] = None
    """
    Routing number
    """

    transfer_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transferType"),
        pydantic.Field(alias="transferType", description="Transfer type (e.g., wire, ach)"),
    ] = None
    """
    Transfer type (e.g., wire, ach)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
