# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawEventsClient, RawEventsClient
from .types.list_events_request_aggregate_type import ListEventsRequestAggregateType
from .types.list_events_request_sort_by import ListEventsRequestSortBy
from .types.list_events_request_sort_order import ListEventsRequestSortOrder
from .types.list_events_response import ListEventsResponse


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ListEventsRequestSortBy] = None,
        sort_order: typing.Optional[ListEventsRequestSortOrder] = None,
        aggregate_type: typing.Optional[ListEventsRequestAggregateType] = None,
        merchant_id: typing.Optional[str] = None,
        aggregate_id: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEventsResponse:
        """
        Retrieve a paginated list of external events. Filter by aggregate type, merchant, or event name.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (0-indexed)

        page_size : typing.Optional[int]
            Number of records per page

        sort_by : typing.Optional[ListEventsRequestSortBy]
            Field to sort by

        sort_order : typing.Optional[ListEventsRequestSortOrder]
            Sort order

        aggregate_type : typing.Optional[ListEventsRequestAggregateType]
            Filter by aggregate type

        merchant_id : typing.Optional[str]
            Filter by merchant ID

        aggregate_id : typing.Optional[str]
            Filter by aggregate ID

        name : typing.Optional[str]
            Filter by event name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEventsResponse
            Paginated list of external events

        Examples
        --------
        from mesta import Mesta

        client = Mesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )
        client.events.list()
        """
        _response = self._raw_client.list(
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            aggregate_type=aggregate_type,
            merchant_id=merchant_id,
            aggregate_id=aggregate_id,
            name=name,
            request_options=request_options,
        )
        return _response.data


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort_by: typing.Optional[ListEventsRequestSortBy] = None,
        sort_order: typing.Optional[ListEventsRequestSortOrder] = None,
        aggregate_type: typing.Optional[ListEventsRequestAggregateType] = None,
        merchant_id: typing.Optional[str] = None,
        aggregate_id: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListEventsResponse:
        """
        Retrieve a paginated list of external events. Filter by aggregate type, merchant, or event name.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number (0-indexed)

        page_size : typing.Optional[int]
            Number of records per page

        sort_by : typing.Optional[ListEventsRequestSortBy]
            Field to sort by

        sort_order : typing.Optional[ListEventsRequestSortOrder]
            Sort order

        aggregate_type : typing.Optional[ListEventsRequestAggregateType]
            Filter by aggregate type

        merchant_id : typing.Optional[str]
            Filter by merchant ID

        aggregate_id : typing.Optional[str]
            Filter by aggregate ID

        name : typing.Optional[str]
            Filter by event name

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEventsResponse
            Paginated list of external events

        Examples
        --------
        import asyncio

        from mesta import AsyncMesta

        client = AsyncMesta(
            api_secret="YOUR_API_SECRET",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page=page,
            page_size=page_size,
            sort_by=sort_by,
            sort_order=sort_order,
            aggregate_type=aggregate_type,
            merchant_id=merchant_id,
            aggregate_id=aggregate_id,
            name=name,
            request_options=request_options,
        )
        return _response.data
