# This file was auto-generated by Fern from our API Definition.

import typing

ListWithdrawalsRequestStatus = typing.Union[
    typing.Literal[
        "created", "screening", "debiting", "withdrawing", "completed", "failed", "rejected", "needs_reconciliation"
    ],
    typing.Any,
]
