# This file was auto-generated by Fern from our API Definition.

import typing

ListWithdrawalsRequestChain = typing.Union[
    typing.Literal["ethereum", "polygon", "solana", "tron", "stellar"], typing.Any
]
