# This file was auto-generated by Fern from our API Definition.

import typing

ListWithdrawalsRequestCurrency = typing.Union[
    typing.Literal["USDC_ETH", "USDC_POL", "USDC_SOL", "USDT_ETH", "USDT_POL", "USDT_SOL", "USDT_TRX"], typing.Any
]
