# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from .get_ubo_rules_v2senders_response_data_rules_ubo_required_fields_item_nested_fields_item import (
    GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem,
)


class GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItem(UniversalBaseModel):
    field: typing.Optional[str] = pydantic.Field(default=None)
    """
    Field name (e.g., firstName, lastName, identity)
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable description of the field
    """

    nested_fields: typing_extensions.Annotated[
        typing.Optional[typing.List[GetUboRulesV2SendersResponseDataRulesUboRequiredFieldsItemNestedFieldsItem]],
        FieldMetadata(alias="nestedFields"),
        pydantic.Field(
            alias="nestedFields",
            description="Nested fields. For identity, the documentType field includes supportedDocumentTypes.",
        ),
    ] = None
    """
    Nested fields. For identity, the documentType field includes supportedDocumentTypes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
