# This file was auto-generated by Fern from our API Definition.

import typing

GetWalletAddressesResponseDataOwnerType = typing.Union[typing.Literal["merchant", "sender", "organization"], typing.Any]
