# This file was auto-generated by Fern from our API Definition.

import typing

DocumentType = typing.Union[
    typing.Literal["invoice", "payslip", "employment_contract", "inter_company_agreement", "other"], typing.Any
]
