# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .fiat_deposit_detail_deposit_details_routing_codes_item import FiatDepositDetailDepositDetailsRoutingCodesItem


class FiatDepositDetailDepositDetails(UniversalBaseModel):
    """
    Details of the deposit transaction from the bank
    """

    depositor_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="depositorName"),
        pydantic.Field(alias="depositorName", description="Name of the depositor"),
    ] = None
    """
    Name of the depositor
    """

    depositor_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="depositorAddress"),
        pydantic.Field(alias="depositorAddress", description="Address of the depositor"),
    ] = None
    """
    Address of the depositor
    """

    depositor_bank_account_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="depositorBankAccountNumber"),
        pydantic.Field(alias="depositorBankAccountNumber", description="Bank account number of the depositor"),
    ] = None
    """
    Bank account number of the depositor
    """

    depositor_bank_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="depositorBankName"),
        pydantic.Field(alias="depositorBankName", description="Name of the depositor's bank"),
    ] = None
    """
    Name of the depositor's bank
    """

    depositor_bank_country: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="depositorBankCountry"),
        pydantic.Field(alias="depositorBankCountry", description="Country of the depositor's bank"),
    ] = None
    """
    Country of the depositor's bank
    """

    routing_codes: typing_extensions.Annotated[
        typing.Optional[typing.List[FiatDepositDetailDepositDetailsRoutingCodesItem]],
        FieldMetadata(alias="routingCodes"),
        pydantic.Field(alias="routingCodes", description="Routing codes associated with the deposit"),
    ] = None
    """
    Routing codes associated with the deposit
    """

    wire_routing_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="wireRoutingNumber"),
        pydantic.Field(alias="wireRoutingNumber", description="Wire routing number"),
    ] = None
    """
    Wire routing number
    """

    sort_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sortCode"),
        pydantic.Field(alias="sortCode", description="Sort code for UK bank transfers"),
    ] = None
    """
    Sort code for UK bank transfers
    """

    payment_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paymentType"),
        pydantic.Field(alias="paymentType", description="Type of payment"),
    ] = None
    """
    Type of payment
    """

    transaction_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transactionDate"),
        pydantic.Field(alias="transactionDate", description="Date and time of the transaction"),
    ] = None
    """
    Date and time of the transaction
    """

    transaction_reference: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transactionReference"),
        pydantic.Field(alias="transactionReference", description="Reference string for the transaction"),
    ] = None
    """
    Reference string for the transaction
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
