# This file was auto-generated by Fern from our API Definition.

import typing

from .bank_account import BankAccount
from .crypto_wallet_info import CryptoWalletInfo
from .instapay_info import InstapayInfo
from .mobile_money_info import MobileMoneyInfo
from .pix_info import PixInfo
from .spei_info import SpeiInfo
from .swiftpay_pesonet_info import SwiftpayPesonetInfo

IndividualBeneficiaryPaymentInfo = typing.Union[
    BankAccount, PixInfo, SwiftpayPesonetInfo, InstapayInfo, SpeiInfo, MobileMoneyInfo, CryptoWalletInfo
]
