# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .stablecoin_deposit_status import StablecoinDepositStatus


class StablecoinDeposit(UniversalBaseModel):
    """
    Stablecoin deposit object for merchant access
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the deposit
    """

    amount: str = pydantic.Field()
    """
    Deposit amount (decimal with 2 decimal places)
    """

    currency: str = pydantic.Field()
    """
    The stablecoin token and chain, e.g. USDC_ETH, USDT_TRX, USDC_SOL
    """

    transaction_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="transactionId"),
        pydantic.Field(alias="transactionId", description="Associated transaction ID"),
    ] = None
    """
    Associated transaction ID
    """

    merchant_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="merchantId"), pydantic.Field(alias="merchantId", description="Merchant ID")
    ]
    """
    Merchant ID
    """

    sender_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="senderId"),
        pydantic.Field(
            alias="senderId",
            description="Sender ID. null for pooled merchant account deposits — merchant-level top-ups carry no sender attribution.",
        ),
    ] = None
    """
    Sender ID. null for pooled merchant account deposits — merchant-level top-ups carry no sender attribution.
    """

    source_wallet_address: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sourceWalletAddress"),
        pydantic.Field(alias="sourceWalletAddress", description="Source blockchain wallet address"),
    ]
    """
    Source blockchain wallet address
    """

    deposit_wallet_address_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="depositWalletAddressId"),
        pydantic.Field(alias="depositWalletAddressId", description="Destination wallet address ID"),
    ]
    """
    Destination wallet address ID
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Creation timestamp"),
    ] = None
    """
    Creation timestamp
    """

    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Last update timestamp"),
    ] = None
    """
    Last update timestamp
    """

    status: typing.Optional[StablecoinDepositStatus] = pydantic.Field(default=None)
    """
    Current status of the stablecoin deposit
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
