# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .verify_sender_requirements_blocker_fields_item_document_type import (
    VerifySenderRequirementsBlockerFieldsItemDocumentType,
)


class VerifySenderRequirementsBlockerFieldsItem(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public subject property, never an internal canonical key.
    """

    label: str
    document_type: typing_extensions.Annotated[
        typing.Optional[VerifySenderRequirementsBlockerFieldsItemDocumentType],
        FieldMetadata(alias="documentType"),
        pydantic.Field(alias="documentType", description="For document fields, the exact upload `type`."),
    ] = None
    """
    For document fields, the exact upload `type`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
